# 1. Imports and File selection

In [2]:
import io
import ipywidgets as widgets
import math
import numpy
import psycopg
import pandas as pd
import requests
import sqlite3
import sys
import tqdm
import warnings

from backend_config import load_config
from ipyfilechooser import FileChooser
from scipy import stats
from scipy.stats import ttest_ind
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert
from sqlite3 import Error
from sqlite3 import IntegrityError

## Select Baseline .csv File

In [3]:
starting_directory = '/Volumes'
baseline_chooser = FileChooser(starting_directory)
display(baseline_chooser)

FileChooser(path='/Volumes', filename='', title='', show_hidden=False, select_desc='Select', change_desc='Chan…

## Select Tap .csv File

In [4]:
tap_chooser=FileChooser('/Volumes')
display(tap_chooser)

FileChooser(path='/Volumes', filename='', title='', show_hidden=False, select_desc='Select', change_desc='Chan…

## Select Post Stimulus Arousal .csv File

In [5]:
psa_chooser = FileChooser('/Volumes')
display(psa_chooser)

FileChooser(path='/Volumes', filename='', title='', show_hidden=False, select_desc='Select', change_desc='Chan…

In [6]:
screens = ['PD_Screen', 'ASD_Screen', 'G-Proteins_Screen', 'Glia_Genes_Screen', 
           'Neuron_Genes_Screen', 'PD_GWAS_Locus22_Screen', 'PD_GWAS_Locus71_Screen', 'ASD_WGS_Screen', 'Miscellaneous']

screen_chooser = widgets.Select(options=screens, value=screens[0], description='Screen:')
display(screen_chooser)

Select(description='Screen:', options=('PD_Screen', 'ASD_Screen', 'G-Proteins_Screen', 'Glia_Genes_Screen', 'N…

In [7]:
Screen=screen_chooser.value
folder_path=baseline_chooser.selected_path
print(folder_path)

/Volumes/RankinLabMehak_SSD/Glia_Genes_Screen_2025

## Read baseline, tap and post stimulus arousal (psa) data

In [8]:
# Read the baseline file
baseline_output = pd.read_csv(baseline_chooser.selected, index_col=0)#.drop(columns=['index'])

print(f"\nShape of the baseline .csv file: {baseline_output.shape}")

# Print the first five rows of the file
baseline_output.head()

Shape of the baseline .csv file: (707599, 21)

,Time,n,Number,Speed,Interval Speed,Bias,Morphwidth,Midline,Area,Angular Speed,...,Kink,Curve,Crab,Pathlength,Plate_id,Date,Screen,dataset,Gene,Allele
12182,490.041,14,12,0.0270,0.0186,0.083,0.0653,0.7677,0.069255,4.3,...,52.2,30.1,0.0034,3.168,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2
12183,490.082,14,12,0.0359,0.0241,0.083,0.0665,0.7662,0.070288,6.0,...,52.4,29.7,0.0102,3.169,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2
12184,490.119,14,12,0.0323,0.0246,0.083,0.0665,0.7822,0.071503,5.5,...,52.6,29.6,0.0089,3.169,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2
12185,490.138,14,12,0.0318,0.0241,0.083,0.0684,0.7796,0.072475,5.1,...,51.1,29.4,0.0070,3.169,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2
12186,490.183,14,12,0.0281,0.0176,0.083,0.0677,0.7779,0.071381,4.6,...,51.2,29.9,0.0071,3.170,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2

In [9]:
# Read the tap file
tap_output = pd.read_csv(tap_chooser.selected, index_col=0)

print(f"\nShape of the psa .csv file: {tap_output.shape}")

# Print the first five rows of the file
tap_output.head()

Shape of the psa .csv file: (9695, 13)

,time,dura,dist,prob,speed,plate,Date,Plate_id,Screen,taps,dataset,Gene,Allele
0,599.983,2.22,0.562,1.000000,0.253153,1,20240724,20240724_023625_A0724,Glia_Genes_Screen,1.0,AMshABLATE_nsIs109,AMshABLATE,nsIs109
1,609.979,1.45,0.371,0.545455,0.255862,1,20240724,20240724_023625_A0724,Glia_Genes_Screen,2.0,AMshABLATE_nsIs109,AMshABLATE,nsIs109
2,619.996,2.11,0.669,0.520000,0.317062,1,20240724,20240724_023625_A0724,Glia_Genes_Screen,3.0,AMshABLATE_nsIs109,AMshABLATE,nsIs109
3,629.971,1.59,0.422,0.809524,0.265409,1,20240724,20240724_023625_A0724,Glia_Genes_Screen,4.0,AMshABLATE_nsIs109,AMshABLATE,nsIs109
4,639.968,1.50,0.378,0.895833,0.252000,1,20240724,20240724_023625_A0724,Glia_Genes_Screen,5.0,AMshABLATE_nsIs109,AMshABLATE,nsIs109

In [10]:
# Read the psa file
psa_output = pd.read_csv(psa_chooser.selected, index_col=0)

for cols in ['Speed',
            #   'Interval Speed',
       'Bias', 'Morphwidth', 'Midline', 'Area', 'Angular Speed',
       'Aspect Ratio', 'Kink', 'Curve', 'Crab', 'Pathlength']:
    psa_output.rename(columns={cols: f"PSA {cols}"}, inplace=True)

print(f"\nShape of the tap .csv file: {psa_output.shape}")

# Print the first five rows of the file
psa_output.head()

Shape of the tap .csv file: (9857, 23)

,Experiment,Screen,Date,Plate_id,Gene,Allele,dataset,taps,Time,n,...,Tap,PSA Morphwidth,PSA Midline,PSA Area,PSA Angular Speed,PSA Aspect Ratio,PSA Kink,PSA Curve,PSA Crab,PSA Pathlength
0,1,Glia_Genes_Screen,20241024,20241024_171133_B1024,N2,N2,N2,1.0,607.017,15.000000,...,0.0,0.063419,0.774055,0.071953,5.437097,0.323339,66.690323,34.417742,0.007847,2.674403
1,1,Glia_Genes_Screen,20241024,20241024_171133_B1024,N2,N2,N2,2.0,617.025,16.193548,...,0.0,0.069426,0.794218,0.077992,13.196774,0.394581,70.537097,37.046774,0.013332,2.905065
2,1,Glia_Genes_Screen,20241024,20241024_171133_B1024,N2,N2,N2,3.0,627.020,17.000000,...,0.0,0.074361,0.819671,0.083514,9.058065,0.339935,72.608065,30.751613,0.012123,2.678081
3,1,Glia_Genes_Screen,20241024,20241024_171133_B1024,N2,N2,N2,4.0,637.020,20.000000,...,0.0,0.080366,0.819053,0.085719,8.482258,0.295935,49.640323,31.625806,0.012297,2.752871
4,1,Glia_Genes_Screen,20241024,20241024_171133_B1024,N2,N2,N2,5.0,647.075,20.629630,...,0.0,0.077781,0.849924,0.088974,4.809259,0.261130,50.259259,29.918519,0.007341,3.041685

In [11]:
psa_output.columns

Index(['Experiment', 'Screen', 'Date', 'Plate_id', 'Gene', 'Allele', 'dataset',
       'taps', 'Time', 'n', 'Number', 'PSA Speed', 'PSA Bias', 'Tap',
       'PSA Morphwidth', 'PSA Midline', 'PSA Area', 'PSA Angular Speed',
       'PSA Aspect Ratio', 'PSA Kink', 'PSA Curve', 'PSA Crab',
       'PSA Pathlength'],
      dtype='object')

### Merge PSA with Tap response

In [29]:
tap_psa_output = pd.merge(
    tap_output, psa_output.drop(columns=['Experiment', 'Time', 'Tap', 'PSA Morphwidth', 
                                         'PSA Midline', 'PSA Area', 'PSA Angular Speed',]),
    how='outer', 
    on=['dataset', 'Gene', 'Allele', 'Date', 'Plate_id', 'Screen', "taps" ] 
)

tap_psa_output = tap_psa_output[['dataset', 'Gene', 'Allele', 'Date', 'Plate_id', 'plate', 
                                 'Screen', 'taps', 'time', 'dura', 'dist', 'prob', 'speed',
                                 'PSA Speed', 
                                #  'PSA Interval Speed', 
                                 'PSA Bias',
                                 'PSA Aspect Ratio', 'PSA Kink', 'PSA Curve', 'PSA Crab'
                                 ]]

print(f"Shape of the dataframe: {tap_psa_output.shape}")

tap_psa_output.rename(columns={
    # 'prob': 'Probability',
    # 'dura': 'Duration',
    # 'speed': 'Speed'
}, inplace=True)

tap_psa_output.head()

Shape of the dataframe: (9858, 19)

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,taps,time,dura,dist,prob,speed,PSA Speed,PSA Bias,PSA Aspect Ratio,PSA Kink,PSA Curve,PSA Crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,1.0,599.983,2.22,0.562,1.000000,0.253153,0.084048,0.213983,0.463328,83.258621,41.187931,0.017031
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,2.0,609.979,1.45,0.371,0.545455,0.255862,0.162728,0.346862,0.398190,65.177586,36.906897,0.024748
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,3.0,619.996,2.11,0.669,0.520000,0.317062,0.199815,0.793278,0.351426,56.307407,34.988889,0.026074
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,4.0,629.971,1.59,0.422,0.809524,0.265409,0.207721,0.873397,0.324241,51.543103,34.353448,0.023929
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,5.0,639.968,1.50,0.378,0.895833,0.252000,0.213855,0.889967,0.284367,43.355000,31.720000,0.021453

In [22]:
# tap_psa_output.to_csv("tap_psa_output.csv")

# 2. DataFrame preparation

### 2.1. Tap & PSA Data

In [37]:
# Dataframe for first tap
PD_first_tap = (
    tap_psa_output[(tap_psa_output.taps==1)]
    .reset_index().drop(columns="index")
    .rename(columns={"dura": "init_dura", "prob": "init_prob", "speed": "init_speed",
                     "PSA Speed": "init_psa_speed",
                     "PSA Bias": "init_psa_bias",
                     "PSA Aspect Ratio": "init_psa_aspect_ratio",
                     "PSA Kink": "init_psa_kink",
                     "PSA Curve": "init_psa_curve",
                     "PSA Crab": "init_psa_crab"}))
PD_first_tap.head()

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,taps,time,init_dura,dist,init_prob,init_speed,init_psa_speed,init_psa_bias,init_psa_aspect_ratio,init_psa_kink,init_psa_curve,init_psa_crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,1.0,599.983,2.22,0.562,1.000000,0.253153,0.084048,0.213983,0.463328,83.258621,41.187931,0.017031
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_032303_A0724,2.0,Glia_Genes_Screen,1.0,599.997,1.82,0.408,0.666667,0.224176,0.054834,0.100021,0.378085,58.204255,36.625532,0.011026
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101025_B0724,3.0,Glia_Genes_Screen,1.0,599.965,2.56,0.457,0.844444,0.178516,0.055250,0.189467,0.411167,61.946667,37.966667,0.010273
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101818_C0724,4.0,Glia_Genes_Screen,1.0,599.940,2.95,0.491,0.760870,0.166441,0.077695,0.132632,0.425526,68.055263,37.826316,0.014916
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_110244_B0724,5.0,Glia_Genes_Screen,1.0,599.982,2.50,0.421,0.764706,0.168400,0.059863,0.164800,0.410067,70.800000,38.313333,0.010830

In [38]:
# Dataframe for recovery taps
PD_recov_taps = (
    tap_psa_output[(tap_psa_output.taps==31)]
    .reset_index().drop(columns="index")
    .rename(columns={"dura": "recov_dura", "prob": "recov_prob", "speed":"recov_speed",
                     "PSA Speed": "recov_psa_speed",
                     "PSA Bias": "recov_psa_bias",
                     "PSA Aspect Ratio": "recov_psa_aspect_ratio",
                     "PSA Kink": "recov_psa_kink",
                     "PSA Curve": "recov_psa_curve",
                     "PSA Crab": "recov_psa_crab"})
)

PD_recov_taps.head()

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,taps,time,recov_dura,dist,recov_prob,recov_speed,recov_psa_speed,recov_psa_bias,recov_psa_aspect_ratio,recov_psa_kink,recov_psa_curve,recov_psa_crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,31.0,1189.985,1.51,0.263,0.828571,0.174172,0.048078,0.042478,0.248565,49.565217,29.921739,0.009287
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_032303_A0724,2.0,Glia_Genes_Screen,31.0,1189.939,1.05,0.190,0.630435,0.180952,0.034445,0.034000,0.262050,42.880000,28.595000,0.007000
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101025_B0724,3.0,Glia_Genes_Screen,31.0,1189.930,2.11,0.271,0.886364,0.128436,0.029463,0.157842,0.287895,52.957895,30.031579,0.004158
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101818_C0724,4.0,Glia_Genes_Screen,31.0,1189.965,1.69,0.240,0.822222,0.142012,0.023255,0.031500,0.284050,51.390000,28.180000,0.004620
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_110244_B0724,5.0,Glia_Genes_Screen,31.0,1189.967,1.95,0.265,0.973684,0.135897,0.033947,0.146278,0.350333,61.177778,30.227778,0.006758

In [39]:
# Dataframe for last three taps
PD_final_taps = (
    tap_psa_output[(tap_psa_output.taps >= 28) & (tap_psa_output.taps <= 30)]
    .groupby(["dataset", "Date","Plate_id","Screen","Gene","Allele","plate"])
    .mean()
    .reset_index()
    .rename(columns={"dura": "final_dura", "prob": "final_prob", "speed": "final_speed",
                     "PSA Speed": "final_psa_speed",
                     "PSA Bias": "final_psa_bias",
                     "PSA Aspect Ratio": "final_psa_aspect_ratio",
                     "PSA Kink": "final_psa_kink",
                     "PSA Curve": "final_psa_curve",
                     "PSA Crab": "final_psa_crab"}, errors="raise")
)

PD_final_taps.head()

,dataset,Date,Plate_id,Screen,Gene,Allele,plate,taps,time,final_dura,dist,final_prob,final_speed,final_psa_speed,final_psa_bias,final_psa_aspect_ratio,final_psa_kink,final_psa_curve,final_psa_crab
0,AMshABLATE_nsIs109,20240724,20240724_023625_A0724,Glia_Genes_Screen,AMshABLATE,nsIs109,1.0,29.0,879.970333,0.866667,0.144333,0.419780,0.167793,0.071447,0.356165,0.294409,48.176604,30.837899,0.009278
1,AMshABLATE_nsIs109,20240724,20240724_032303_A0724,Glia_Genes_Screen,AMshABLATE,nsIs109,2.0,29.0,879.969333,0.906667,0.144667,0.336761,0.160319,0.077325,0.338699,0.276696,48.804288,30.475179,0.010215
2,AMshABLATE_nsIs109,20240724,20240724_101025_B0724,Glia_Genes_Screen,AMshABLATE,nsIs109,3.0,29.0,879.936000,1.480000,0.215667,0.611189,0.145128,0.073460,0.472218,0.298760,49.892843,29.745665,0.009122
3,AMshABLATE_nsIs109,20240724,20240724_101818_C0724,Glia_Genes_Screen,AMshABLATE,nsIs109,4.0,29.0,879.949000,1.530000,0.208000,0.567925,0.136765,0.068190,0.500335,0.282816,47.092560,29.314862,0.009246
4,AMshABLATE_nsIs109,20240724,20240724_110244_B0724,Glia_Genes_Screen,AMshABLATE,nsIs109,5.0,29.0,879.947667,1.466667,0.217333,0.503704,0.148535,0.070264,0.513896,0.301485,49.370824,30.257097,0.008544

In [41]:
# Dataframe to analyse habituation behaviour after merging first tap and final taps

PD_habit_levels = pd.merge(
    PD_first_tap, 
    PD_final_taps, 
    on =['dataset', 'plate', "Plate_id", "Screen", "Gene", "Allele", "Date"], how ='left'
).drop(columns=['time_x','time_y','dist_x','dist_y', 'taps_x', 'taps_y']).dropna()

PD_habit_levels['habit_dura'] = PD_habit_levels['init_dura'] - PD_habit_levels['final_dura']
PD_habit_levels['habit_prob'] = PD_habit_levels['init_prob'] - PD_habit_levels['final_prob']
PD_habit_levels['habit_speed'] = PD_habit_levels['init_speed'] - PD_habit_levels['final_speed']
PD_habit_levels['habit_psa_speed'] = PD_habit_levels['init_psa_speed'] - PD_habit_levels['final_psa_speed']
PD_habit_levels['habit_psa_bias'] = PD_habit_levels['init_psa_bias'] - PD_habit_levels['final_psa_bias']
PD_habit_levels['habit_psa_aspect_ratio'] = PD_habit_levels['init_psa_aspect_ratio'] - PD_habit_levels['final_psa_aspect_ratio']
PD_habit_levels['habit_psa_kink'] = PD_habit_levels['init_psa_kink'] - PD_habit_levels['final_psa_kink']
PD_habit_levels['habit_psa_curve'] = PD_habit_levels['init_psa_curve'] - PD_habit_levels['final_psa_curve']
PD_habit_levels['habit_psa_crab'] = PD_habit_levels['init_psa_crab'] - PD_habit_levels['final_psa_crab']

In [43]:
# Continue to analyse habituation behaviour after merging with recovery taps

if PD_recov_taps.empty:
    PD_habituation = pd.merge(PD_habit_levels, PD_recov_taps, on =['dataset','plate',"Plate_id","Screen","Gene","Allele","Date"], how ='outer')
else:
    PD_habituation = pd.merge(PD_habit_levels, PD_recov_taps, on =['dataset','plate',"Plate_id","Screen","Gene","Allele","Date"], how ='left')

if Screen not in ['Neuron_Genes_Screen', 'G-Proteins_Screen']:
    PD_habituation = PD_habituation.dropna() 

PD_habituation['recovery_dura']=(PD_habituation.recov_dura-PD_habituation.init_dura)/PD_habituation.init_dura*100
PD_habituation['recovery_prob']=(PD_habituation.recov_prob-PD_habituation.init_prob)/PD_habituation.init_prob*100
PD_habituation['recovery_speed']=(PD_habituation.recov_speed-PD_habituation.init_speed)/PD_habituation.init_speed*100
PD_habituation['recovery_psa_speed']=(PD_habituation.recov_psa_speed-PD_habituation.init_psa_speed)/PD_habituation.init_psa_speed*100
PD_habituation['recovery_psa_bias']=(PD_habituation.recov_psa_bias-PD_habituation.init_psa_bias)/PD_habituation.init_psa_bias*100
PD_habituation['recovery_psa_aspect_ratio']=(PD_habituation.recov_psa_aspect_ratio-PD_habituation.init_psa_aspect_ratio)/PD_habituation.init_psa_aspect_ratio*100
PD_habituation['recovery_psa_kink']=(PD_habituation.recov_psa_kink-PD_habituation.init_psa_kink)/PD_habituation.init_psa_kink*100
PD_habituation['recovery_psa_curve']=(PD_habituation.recov_psa_curve-PD_habituation.init_psa_curve)/PD_habituation.init_psa_curve*100
PD_habituation['recovery_psa_crab']=(PD_habituation.recov_psa_crab-PD_habituation.init_psa_crab)/PD_habituation.init_psa_crab*100

PD_habituation['memory_retention_dura']=(PD_habituation.recov_dura-PD_habituation.final_dura)
PD_habituation['memory_retention_prob']=(PD_habituation.recov_prob-PD_habituation.final_prob)
PD_habituation['memory_retention_speed']=(PD_habituation.recov_speed-PD_habituation.final_speed)
PD_habituation['memory_retention_psa_speed']=(PD_habituation.recov_psa_speed-PD_habituation.final_psa_speed)
PD_habituation['memory_retention_psa_bias']=(PD_habituation.recov_psa_bias-PD_habituation.final_psa_bias)
PD_habituation['memory_retention_psa_aspect_ratio']=(PD_habituation.recov_psa_aspect_ratio-PD_habituation.final_psa_aspect_ratio)
PD_habituation['memory_retention_psa_kink']=(PD_habituation.recov_psa_kink-PD_habituation.final_psa_kink)
PD_habituation['memory_retention_psa_curve']=(PD_habituation.recov_psa_curve-PD_habituation.final_psa_curve)
PD_habituation['memory_retention_psa_crab']=(PD_habituation.recov_psa_crab-PD_habituation.final_psa_crab)


# Rename `PD_habituation` to `tap_data` based on the condition below
if Screen in ['Neuron_Genes_Screen', 'G-Proteins_Screen']:
    tap_data=PD_habituation.dropna(subset = ['dataset', 'Gene', 'Allele','Date', 'Plate_id', 'plate', 'Screen', 
                                             'init_dura', 'init_prob', 'init_speed', 'init_psa_speed', 'init_psa_bias',
                                             'init_psa_aspect_ratio','init_psa_kink','init_psa_curve','init_psa_crab',
                                            'final_dura', 'final_prob', 'final_psa_speed', 'final_psa_bias',
                                            'final_psa_aspect_ratio','final_psa_kink','final_psa_curve','final_psa_crab',
                                            'final_speed', 'habit_dura', 'habit_prob', 'habit_speed','habit_psa_speed','habit_psa_bias',
                                            'habit_psa_aspect_ratio','habit_psa_kink','habit_psa_curve','habit_psa_crab'])
else:
    tap_data=PD_habituation.dropna() 


# Display final dataframe
tap_data.head()

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,init_dura,init_prob,init_speed,...,recovery_psa_crab,memory_retention_dura,memory_retention_prob,memory_retention_speed,memory_retention_psa_speed,memory_retention_psa_bias,memory_retention_psa_aspect_ratio,memory_retention_psa_kink,memory_retention_psa_curve,memory_retention_psa_crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,2.22,1.000000,0.253153,...,-45.470391,0.643333,0.408791,0.006379,-0.023369,-0.313686,-0.045844,1.388614,-0.916159,0.000009
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_032303_A0724,2.0,Glia_Genes_Screen,1.82,0.666667,0.224176,...,-36.511000,0.143333,0.293673,0.020633,-0.042880,-0.304699,-0.014646,-5.924288,-1.880179,-0.003215
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101025_B0724,3.0,Glia_Genes_Screen,2.56,0.844444,0.178516,...,-59.527306,0.630000,0.275175,-0.016692,-0.043997,-0.314376,-0.010865,3.065052,0.285914,-0.004964
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101818_C0724,4.0,Glia_Genes_Screen,2.95,0.760870,0.166441,...,-69.026112,0.160000,0.254298,0.005247,-0.044935,-0.468835,0.001234,4.297440,-1.134862,-0.004626
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_110244_B0724,5.0,Glia_Genes_Screen,2.50,0.764706,0.168400,...,-37.596183,0.483333,0.469981,-0.012638,-0.036317,-0.367618,0.048848,11.806953,-0.029319,-0.001786

In [48]:
tap_psa_output

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,taps,time,dura,dist,prob,speed,PSA Speed,PSA Bias,PSA Aspect Ratio,PSA Kink,PSA Curve,PSA Crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,1.0,599.983,2.22,0.562,1.000000,0.253153,0.084048,0.213983,0.463328,83.258621,41.187931,0.017031
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,2.0,609.979,1.45,0.371,0.545455,0.255862,0.162728,0.346862,0.398190,65.177586,36.906897,0.024748
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,3.0,619.996,2.11,0.669,0.520000,0.317062,0.199815,0.793278,0.351426,56.307407,34.988889,0.026074
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,4.0,629.971,1.59,0.422,0.809524,0.265409,0.207721,0.873397,0.324241,51.543103,34.353448,0.023929
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,5.0,639.968,1.50,0.378,0.895833,0.252000,0.213855,0.889967,0.284367,43.355000,31.720000,0.021453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9853,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_220015_C0313,12.0,Glia_Genes_Screen,27.0,859.929,0.41,0.075,0.364865,0.182927,0.121700,0.824222,0.287528,42.944444,29.627778,0.012017
9854,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_220015_C0313,12.0,Glia_Genes_Screen,28.0,869.928,0.73,0.117,0.409091,0.160274,0.114174,0.773632,0.298079,46.328947,30.213158,0.012016
9855,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_220015_C0313,12.0,Glia_Genes_Screen,29.0,879.967,1.10,0.186,0.436364,0.169091,0.121276,0.752512,0.300122,43.748780,30.168293,0.012920
9856,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_220015_C0313,12.0,Glia_Genes_Screen,30.0,889.963,1.12,0.160,0.461538,0.142857,0.112712,0.786091,0.288394,42.569697,29.084848,0.011427
9857,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_220015_C0313,12.0,Glia_Genes_Screen,31.0,1189.999,2.24,0.477,0.891892,0.212946,0.072732,0.275676,0.370811,62.135135,33.459459,0.010484

In [64]:
tap_psa_output_max = tap_psa_output.groupby(['dataset', 'Gene', 'Allele', 'Date', 'Plate_id', 'plate', 'Screen'], as_index = False).max().round(4).rename(
    columns = {
        'PSA Speed': 'max_psa_speed',
        'PSA Bias': 'max_psa_bias',
        'PSA Aspect Ratio': 'max_psa_aspect_ratio',
        'PSA Kink': 'max_psa_kink',
        'PSA Curve': 'max_psa_curve',
        'PSA Crab': 'max_psa_crab'
    }).drop(columns = ['taps','time','dura','dist','prob','speed'])

tap_psa_output_mean = tap_psa_output.groupby(['dataset','Gene','Allele','Date','Plate_id','plate','Screen'], as_index = False).mean().round(4).rename(
    columns = {
        'prob': 'mean_prob',
        'dura': 'mean_dura',
        'speed': 'mean_speed',
        'PSA Speed': 'mean_psa_speed',
        'PSA Bias': 'mean_psa_bias',
        'PSA Aspect Ratio': 'mean_psa_aspect_ratio',
        'PSA Kink': 'mean_psa_kink',
        'PSA Curve': 'mean_psa_curve',
        'PSA Crab': 'mean_psa_crab'
    }).drop(columns = ['taps','time','dist'])

tap_psa_output_mean.head()

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,mean_dura,mean_prob,mean_speed,mean_psa_speed,mean_psa_bias,mean_psa_aspect_ratio,mean_psa_kink,mean_psa_curve,mean_psa_crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,1.1897,0.6275,0.2029,0.1223,0.5485,0.2915,48.5180,31.5382,0.0141
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_032303_A0724,2.0,Glia_Genes_Screen,1.0994,0.5235,0.1970,0.1063,0.4543,0.2956,49.5745,31.3311,0.0128
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101025_B0724,3.0,Glia_Genes_Screen,1.6574,0.6704,0.1866,0.1172,0.5943,0.2997,48.6269,30.1888,0.0127
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101818_C0724,4.0,Glia_Genes_Screen,1.7213,0.6689,0.1860,0.1184,0.5631,0.3090,49.7521,31.4205,0.0138
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_110244_B0724,5.0,Glia_Genes_Screen,1.6287,0.6182,0.1767,0.1087,0.6113,0.3032,49.0950,30.4203,0.0119

In [67]:
tap_data = pd.merge(PD_habituation, tap_psa_output_max, on =['dataset','plate',"Plate_id","Screen","Gene","Allele","Date"], how ='outer')
tap_data = pd.merge(tap_data, tap_psa_output_mean, on =['dataset','plate',"Plate_id","Screen","Gene","Allele","Date"], how ='outer')

tap_data['sensitization_psa_speed']=(tap_data.max_psa_speed - tap_data.init_psa_speed)
tap_data['sensitization_psa_bias']=(tap_data.max_psa_bias - tap_data.init_psa_bias)
tap_data['sensitization_psa_aspect_ratio']=(tap_data.max_psa_aspect_ratio - tap_data.init_psa_aspect_ratio)   
tap_data['sensitization_psa_kink']=(tap_data.max_psa_kink - tap_data.init_psa_kink)
tap_data['sensitization_psa_curve']=(tap_data.max_psa_curve - tap_data.init_psa_curve)
tap_data['sensitization_psa_crab']=(tap_data.max_psa_crab - tap_data.init_psa_crab)

tap_data

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,init_dura,init_prob,init_speed,...,mean_psa_aspect_ratio,mean_psa_kink,mean_psa_curve,mean_psa_crab,sensitization_psa_speed,sensitization_psa_bias,sensitization_psa_aspect_ratio,sensitization_psa_kink,sensitization_psa_curve,sensitization_psa_crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,2.22,1.000000,0.253153,...,0.2915,48.5180,31.5382,0.0141,0.129852,0.722417,-0.000028,-0.000021,-0.000031,0.009069
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_032303_A0724,2.0,Glia_Genes_Screen,1.82,0.666667,0.224176,...,0.2956,49.5745,31.3311,0.0128,0.125366,0.649579,0.069915,17.899945,0.839068,0.010774
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101025_B0724,3.0,Glia_Genes_Screen,2.56,0.844444,0.178516,...,0.2997,48.6269,30.1888,0.0127,0.160250,0.685533,0.014733,6.523133,0.000033,0.014727
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101818_C0724,4.0,Glia_Genes_Screen,2.95,0.760870,0.166441,...,0.3090,49.7521,31.4205,0.0138,0.131605,0.692568,-0.000026,0.000037,-0.000016,0.011984
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_110244_B0724,5.0,Glia_Genes_Screen,2.50,0.764706,0.168400,...,0.3032,49.0950,30.4203,0.0119,0.143737,0.703800,0.050033,0.190300,-0.000033,0.011670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_134421_A0313,8.0,Glia_Genes_Screen,2.30,0.838710,0.193913,...,0.3122,50.8310,33.1769,0.0139,0.122097,0.867067,0.035183,1.013333,0.953367,0.011245
314,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_200530_B0313,9.0,Glia_Genes_Screen,2.23,0.823529,0.170404,...,0.3049,44.8537,30.0586,0.0133,0.106692,0.830813,0.011692,3.659658,0.340977,0.007813
315,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_205323_C0313,10.0,Glia_Genes_Screen,2.69,0.804878,0.202602,...,0.3286,50.8685,31.2428,0.0120,0.094908,0.901261,0.087584,20.831174,2.764258,0.006061
316,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_215555_B0313,11.0,Glia_Genes_Screen,2.80,0.774194,0.159643,...,0.3270,52.1841,31.2238,0.0122,0.111468,0.901323,0.041627,4.384927,1.453600,0.009927
317,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_220015_C0313,12.0,Glia_Genes_Screen,1.99,0.731707,0.204020,...,0.3276,50.1867,31.2678,0.0134,0.098964,0.913666,0.000036,12.000121,-0.000026,0.006664

In [96]:
print(tap_data.columns.to_list())

['dataset', 'Gene', 'Allele', 'Date', 'Plate_id', 'plate', 'Screen', 'init_dura', 'init_prob', 'init_speed', 'init_psa_speed', 'init_psa_bias', 'init_psa_aspect_ratio', 'init_psa_kink', 'init_psa_curve', 'init_psa_crab', 'final_dura', 'final_prob', 'final_speed', 'final_psa_speed', 'final_psa_bias', 'final_psa_aspect_ratio', 'final_psa_kink', 'final_psa_curve', 'final_psa_crab', 'habit_dura', 'habit_prob', 'habit_speed', 'habit_psa_speed', 'habit_psa_bias', 'habit_psa_aspect_ratio', 'habit_psa_kink', 'habit_psa_curve', 'habit_psa_crab', 'taps', 'time', 'recov_dura', 'dist', 'recov_prob', 'recov_speed', 'recov_psa_speed', 'recov_psa_bias', 'recov_psa_aspect_ratio', 'recov_psa_kink', 'recov_psa_curve', 'recov_psa_crab', 'recovery_dura', 'recovery_prob', 'recovery_speed', 'recovery_psa_speed', 'recovery_psa_bias', 'recovery_psa_aspect_ratio', 'recovery_psa_kink', 'recovery_psa_curve', 'recovery_psa_crab', 'memory_retention_dura', 'memory_retention_prob', 'memory_retention_speed', 'memory_retention_psa_speed', 'memory_retention_psa_bias', 'memory_retention_psa_aspect_ratio', 'memory_retention_psa_kink', 'memory_retention_psa_curve', 'memory_retention_psa_crab', 'max_psa_speed', 'max_psa_bias', 'max_psa_aspect_ratio', 'max_psa_kink', 'max_psa_curve', 'max_psa_crab', 'mean_dura', 'mean_prob', 'mean_speed', 'mean_psa_speed', 'mean_psa_bias', 'mean_psa_aspect_ratio', 'mean_psa_kink', 'mean_psa_curve', 'mean_psa_crab', 'sensitization_psa_speed', 'sensitization_psa_bias', 'sensitization_psa_aspect_ratio', 'sensitization_psa_kink', 'sensitization_psa_curve', 'sensitization_psa_crab']

### 2.2. PSA data

In [ ]:
# # function to calculate Initial, Final, Peak, ect values for specified column (metric)

# def summary_metrics(df, metric = 'PSA Speed'):

#     initial = df[metric].iloc[0]
#     # peak = df[metric].max()
#     peak_id = df[metric].values.argmax() # only used for peak tap calculation
#     peak_tap = df['taps'].iloc[peak_id]
#     # mean = df[metric].mean()
#     sensitization = peak - initial
#     # recovery = df[df['taps']==31][metric] if not df[df['taps']==31].empty else 0
#     # final = df[((df.taps >= 28) & (df.taps <= 30))][metric]
#     # spontaneous_recovery = 100*(initial - recovery)/initial if metric not in ['PSA Aspect Ratio', 'PSA Kink', 'PSA Curve', 'PSA Crab'] else 100*(recovery - initial)/initial
#     # memory_retention = final - recovery if metric not in ['PSA Aspect Ratio', 'PSA Kink', 'PSA Curve', 'PSA Crab'] else recovery - final

    
#     # initial_to_peak = df[metric].iloc[: peak_id+1].mean()
#     # peak_to_recovery = df[metric].iloc[peak_id:].mean()

#     # print(df)
#     # print("-----------------")

    

#     return pd.Series({
#         f'Initial {metric}': initial, 
#         # f'Final {metric}': final,
#         # f'Recovery {metric}': recovery, 
#         f'Peak {metric}': peak,
#         f'Peak Tap Number of {metric}': peak_tap,
#         f'Average {metric}': mean,
#         f'Sensitization of {metric}': sensitization,
#         # f'Habituation of {metric}': habituation,
#         # f'Spontaneous Recovery of {metric}': spontaneous_recovery,
#         # f'Memory Retention of {metric}': memory_retention
#         # f'Initial_to_peak {metric}': initial_to_peak, 
#         # f'Peak_to_recovery {metric}': peak_to_recovery
#         })

In [ ]:
# warnings.filterwarnings('ignore')

# # columns to summarize
# metrics_to_summarize = ['PSA Speed', 'PSA Bias', 'PSA Angular Speed', 
#                         'PSA Aspect Ratio', 'PSA Kink', 'PSA Curve', 'PSA Crab']

# # standard columns
# group_cols = ['Experiment', 'Plate_id', 'Date', 'Screen', 'dataset', 'Gene', 'Allele', 'taps']

# # pass each column to summarise through `summary_metrics` function and merge the summarised values to psa_output
# psa_data = psa_output[group_cols].drop_duplicates()
# for metric in metrics_to_summarize:
#     summary = psa_output.groupby(group_cols).apply(lambda x: summary_metrics(x, metric)).reset_index()
#     psa_data = pd.merge(psa_data, summary, on=group_cols, how='left')

In [ ]:
# psa_data.head()

,Experiment,Plate_id,Date,Screen,dataset,Gene,Allele,taps,Initial PSA Speed,Peak PSA Speed,...,Initial PSA Curve,Peak PSA Curve,Peak Tap Number of PSA Curve,Average PSA Curve,Sensitization of PSA Curve,Initial PSA Crab,Peak PSA Crab,Peak Tap Number of PSA Crab,Average PSA Crab,Sensitization of PSA Crab
0,1,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2,1.0,0.058189,0.058189,...,34.417742,34.417742,1.0,34.417742,0.0,0.007847,0.007847,1.0,0.007847,0.0
1,1,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2,2.0,0.094568,0.094568,...,37.046774,37.046774,2.0,37.046774,0.0,0.013332,0.013332,2.0,0.013332,0.0
2,1,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2,3.0,0.110121,0.110121,...,30.751613,30.751613,3.0,30.751613,0.0,0.012123,0.012123,3.0,0.012123,0.0
3,1,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2,4.0,0.111542,0.111542,...,31.625806,31.625806,4.0,31.625806,0.0,0.012297,0.012297,4.0,0.012297,0.0
4,1,20241024_171133_B1024,20241024,Glia_Genes_Screen,N2,N2,N2,5.0,0.093339,0.093339,...,29.918519,29.918519,5.0,29.918519,0.0,0.007341,0.007341,5.0,0.007341,0.0

# 3. Run Statistics (T-Test and mean sample distance) on Data

## 3.1 Generate dataframes conditioned by `baseline` (True/False) and `allele` (True/False)

In [68]:
def get_output_byplate(output, baseline=["true", "false", "psa"], allele = [False, True]):
    """
    Aggregates data by 'Gene' or 'Allele' and drops 'Plate_id','Date','Screen','dataset', etc

    Parameters:
        output (pd.DataFrame): Input DataFrame (either baseline_output or tap_data)
        baseline (boolean): whether data is baseline (True) or tap response (False)
        allele (boolean): group by allele (True) or group by gene (False)

    Returns:
        A DataFrame with plate-level averages
    """
    
    # columns to delete if baseline = true (baseline)
    if baseline == "true":
        drop_col = ['Plate_id','n','Number','Time','Screen','Date','Allele']
    # columns to delete if baseline = false (tap and psa data)
    elif baseline == "false":
        drop_col = ['Plate_id','Screen','Date','Allele','dist','plate','time',
                       'taps','recov_dura','recov_prob','recov_speed']
    # columns to delete if baseline = psa (psa)
    else: 
        # drop_col = ['Experiment', 'Plate_id', 'Date', 'Screen', 'Allele']
        pass

    drop_col.append('Gene') if allele else drop_col.append('dataset')
     
    output_byplate = output.groupby(
        by=['Plate_id','Date','Screen','dataset','Gene','Allele'],
        as_index=False).mean().drop(columns=drop_col)
    
    return output_byplate

#### 3.1.1 `baseline` = True, `allele` = False

In [72]:
baseline_output_byplate=get_output_byplate(baseline_output, baseline= "true", allele=False)

print(f"Shape: {baseline_output_byplate.shape}")

baseline_output_byplate.head()

Shape: (318, 13)

,Gene,Speed,Interval Speed,Bias,Morphwidth,Midline,Area,Angular Speed,Aspect Ratio,Kink,Curve,Crab,Pathlength
0,AMshABLATE,0.028947,0.025567,-0.008870,0.145966,1.239813,0.190805,2.056068,0.330311,57.238641,29.283398,0.006057,1.904028
1,N2,0.060303,0.072300,0.157983,0.099035,1.213483,0.145692,2.757155,0.252760,41.775481,29.871081,0.007687,7.330147
2,AMshABLATE,0.030928,0.025825,0.000614,0.092516,1.115931,0.127868,2.036695,0.256568,47.684237,28.306229,0.005724,2.600575
3,N2,0.042891,0.048333,0.037748,0.102591,1.214810,0.148884,2.703570,0.271092,49.113430,30.837654,0.007713,4.782460
4,N2,0.113829,0.094346,0.653023,0.119960,1.146936,0.155877,4.156619,0.245972,40.113238,28.564274,0.009363,3.751665

#### 3.1.2 `baseline` = False, `allele` = False

In [73]:
tap_data_byplate=get_output_byplate(tap_data, baseline="false", allele=False)

print(f"Shape: {tap_data_byplate.shape}")

tap_data_byplate.head()

Shape: (318, 73)

,Gene,init_dura,init_prob,init_speed,init_psa_speed,init_psa_bias,init_psa_aspect_ratio,init_psa_kink,init_psa_curve,init_psa_crab,...,mean_psa_aspect_ratio,mean_psa_kink,mean_psa_curve,mean_psa_crab,sensitization_psa_speed,sensitization_psa_bias,sensitization_psa_aspect_ratio,sensitization_psa_kink,sensitization_psa_curve,sensitization_psa_crab
0,AMshABLATE,2.22,1.000000,0.253153,0.084048,0.213983,0.463328,83.258621,41.187931,0.017031,...,0.2915,48.5180,31.5382,0.0141,0.129852,0.722417,-0.000028,-0.000021,-0.000031,0.009069
1,N2,2.64,0.780488,0.233712,0.070634,0.241138,0.363845,61.215517,37.379310,0.011490,...,0.2515,43.1552,30.6509,0.0131,0.130566,0.668362,-0.000045,1.814983,-0.000010,0.008710
2,AMshABLATE,1.82,0.666667,0.224176,0.054834,0.100021,0.378085,58.204255,36.625532,0.011026,...,0.2956,49.5745,31.3311,0.0128,0.125366,0.649579,0.069915,17.899945,0.839068,0.010774
3,N2,2.25,0.840000,0.223556,0.078074,0.163377,0.410113,67.947170,38.194340,0.014130,...,0.2561,43.4531,30.4020,0.0148,0.157926,0.791723,-0.000013,0.000030,-0.000040,0.010970
4,N2,3.62,0.933333,0.269337,0.127673,0.654212,0.411333,70.354545,36.342424,0.019697,...,0.2401,39.2329,28.9175,0.0133,0.099427,0.285288,-0.000033,-0.000045,-0.000024,0.001603

#### 3.1.3 `baseline` = True, `allele` = True

In [74]:
baseline_output_allele_byplate = get_output_byplate(baseline_output,baseline="true", allele=True)

print(f"Shape: {baseline_output_allele_byplate.shape}")

baseline_output_allele_byplate.head()

Shape: (318, 13)

,dataset,Speed,Interval Speed,Bias,Morphwidth,Midline,Area,Angular Speed,Aspect Ratio,Kink,Curve,Crab,Pathlength
0,AMshABLATE_nsIs109,0.028947,0.025567,-0.008870,0.145966,1.239813,0.190805,2.056068,0.330311,57.238641,29.283398,0.006057,1.904028
1,N2,0.060303,0.072300,0.157983,0.099035,1.213483,0.145692,2.757155,0.252760,41.775481,29.871081,0.007687,7.330147
2,AMshABLATE_nsIs109,0.030928,0.025825,0.000614,0.092516,1.115931,0.127868,2.036695,0.256568,47.684237,28.306229,0.005724,2.600575
3,N2,0.042891,0.048333,0.037748,0.102591,1.214810,0.148884,2.703570,0.271092,49.113430,30.837654,0.007713,4.782460
4,N2,0.113829,0.094346,0.653023,0.119960,1.146936,0.155877,4.156619,0.245972,40.113238,28.564274,0.009363,3.751665

#### 3.1.4 `baseline` = False, `allele` = True

In [75]:
tap_data_allele_byplate = get_output_byplate(tap_data, baseline="false", allele=True)

print(f"Shape: {tap_data_allele_byplate.shape}")

tap_data_allele_byplate.head()

Shape: (318, 73)

,dataset,init_dura,init_prob,init_speed,init_psa_speed,init_psa_bias,init_psa_aspect_ratio,init_psa_kink,init_psa_curve,init_psa_crab,...,mean_psa_aspect_ratio,mean_psa_kink,mean_psa_curve,mean_psa_crab,sensitization_psa_speed,sensitization_psa_bias,sensitization_psa_aspect_ratio,sensitization_psa_kink,sensitization_psa_curve,sensitization_psa_crab
0,AMshABLATE_nsIs109,2.22,1.000000,0.253153,0.084048,0.213983,0.463328,83.258621,41.187931,0.017031,...,0.2915,48.5180,31.5382,0.0141,0.129852,0.722417,-0.000028,-0.000021,-0.000031,0.009069
1,N2,2.64,0.780488,0.233712,0.070634,0.241138,0.363845,61.215517,37.379310,0.011490,...,0.2515,43.1552,30.6509,0.0131,0.130566,0.668362,-0.000045,1.814983,-0.000010,0.008710
2,AMshABLATE_nsIs109,1.82,0.666667,0.224176,0.054834,0.100021,0.378085,58.204255,36.625532,0.011026,...,0.2956,49.5745,31.3311,0.0128,0.125366,0.649579,0.069915,17.899945,0.839068,0.010774
3,N2,2.25,0.840000,0.223556,0.078074,0.163377,0.410113,67.947170,38.194340,0.014130,...,0.2561,43.4531,30.4020,0.0148,0.157926,0.791723,-0.000013,0.000030,-0.000040,0.010970
4,N2,3.62,0.933333,0.269337,0.127673,0.654212,0.411333,70.354545,36.342424,0.019697,...,0.2401,39.2329,28.9175,0.0133,0.099427,0.285288,-0.000033,-0.000045,-0.000024,0.001603

In [103]:
# tap_data_allele_byplate[tap_data_allele_byplate.dataset=='N2_XJ1']

#### 3.1.5 `baseline` = "psa" , `allele` = False *Defunct*

In [70]:
# psa_data_byplate = get_output_byplate(psa_data, baseline="psa", allele=False)

# print(f"Shape: {psa_data_byplate.shape}")

# psa_data_byplate.head()

#### 3.1.6 `baseline` = "psa" , `allele` = True

In [71]:
# psa_data_allele_byplate = get_output_byplate(psa_data, baseline="psa", allele=True)

# print(f"Shape: {psa_data_allele_byplate.shape}")

# psa_data_allele_byplate.head()

## 3.2 Calculate Mean Distances and CIs

In [76]:

def extract_phenotypes(df):
    ''' 
    Splits a multi-column DataFrame into a list of DataFrames, each containing one phenotype

    input: 
        df (pd.DataFrame): dataframe with multiple columns (1st column is the index, the other are phenotypes)

    returns:
        list_phenotypes_df: list with 2 columns - one for index and one for phenotype, 
            for how many phenotypes there are in the input
    '''
    list_phenotypes_df = []
    index = df.columns[0]
    for i in df.columns[1:]:
        list_phenotypes_df.append(df[[index, i]].copy())

    return list_phenotypes_df



def ci95(df):
    """
    input: df of 4 columns: index, mean, count, std

    returns: df of 6 columns: index, mean, count, std, ci95_hi, ci95_low

    """
    for metric in df.columns.levels[0]:
        if metric == 'Gene':
            pass
        else:
            ci95_hi = []
            ci95_lo = []
            for i in df[metric].index:
                m = df[metric]['mean'].loc[i]
                c = df[metric]['count'].loc[i]
                s = df[metric]['sem'].loc[i]
                ci95_hi.append(stats.t.interval(confidence=0.95, df=c-1, loc=m, scale=s)[1])
                ci95_lo.append(stats.t.interval(confidence=0.95, df=c-1, loc=m, scale=s)[0])
            df[metric,'ci95_hi'] = ci95_hi
            df[metric,'ci95_lo'] = ci95_lo
            # df[metric,'ci95']=list(zip(ci95_lo,ci95_hi))
            
    return df



def calculate_MSD(list_of_dfs, by):
    new_list_of_dfs = []
    
    for df in list_of_dfs:
        # Get phenotype column name (assuming 2nd column is the metric)
        pheno_col = df.columns[1]
        
        # Calculate statistics
        stats = df.groupby(by)[df.columns[1]].agg(['mean', 'count', 'sem'])

        
        # Convert to MultiIndex if needed (more robust version)
        if not isinstance(stats.columns, pd.MultiIndex):
            stats.columns = pd.MultiIndex.from_tuples([(pheno_col, col) for col in stats.columns])
        
        # Calculate CI
        stats_2 = ci95(stats)
        
        # Get N2 control data
        if Screen == "Neuron_Genes_Screen":
            N2_mask = stats_2.index == 'N2' if by == "Gene" else stats_2.index.isin(['N2_XJ1','N2_N2'])
        else:
            N2_mask = stats_2.index == 'N2'
            
        N2_data = stats_2[N2_mask]
        
        # Subtract N2 values
        stats_2.iloc[:, 0] -= N2_data.iloc[0, 0]  # mean
        stats_2.iloc[:, 3] -= N2_data.iloc[0, 0]  # ci95_hi
        stats_2.iloc[:, 4] -= N2_data.iloc[0, 0]  # ci95_low
        
        new_list_of_dfs.append(stats_2)
    
    return new_list_of_dfs

In [77]:
def calculate_MSD(list_of_dfs, by):
    new_list_of_dfs = []
    
    for df in list_of_dfs:
        # Get phenotype column name (assuming 2nd column is the metric)
        pheno_col = df.columns[1]
        
        # Create proper MultiIndex structure
        stats = df.groupby(by)[df.columns[1]].agg(['mean', 'count', 'sem'])

        # Convert to MultiIndex if needed (more robust version)
        if not isinstance(stats.columns, pd.MultiIndex):
            stats.columns = pd.MultiIndex.from_tuples([(pheno_col, col) for col in stats.columns])
        
        # Calculate CIs
        stats_2 = ci95(stats)
        
        # Get N2 control data
        if Screen == "Neuron_Genes_Screen":
            N2_mask = stats_2.index == 'N2' if by == "Gene" else stats_2.index.isin(['N2_XJ1','N2_N2'])
        else:
            N2_mask = stats_2.index == 'N2'
            
        N2_data = stats_2[N2_mask]
        
        # Subtract N2 values
        stats_2.iloc[:, 0] -= N2_data.iloc[0, 0]  # mean
        stats_2.iloc[:, 3] -= N2_data.iloc[0, 0]  # ci95_hi
        stats_2.iloc[:, 4] -= N2_data.iloc[0, 0]  # ci95_low
        
        new_list_of_dfs.append(stats_2)
    
    return new_list_of_dfs

In [78]:
def get_MSD(list_MSD):
    '''
    input: List of dataframes, each representing a phenotype with calculated MSD.

    returns: Single combined dataframe joining all input dataframes with MSD values.
    '''
    for a in list_MSD:
        if a.columns.levels[0] == list_MSD[0].columns.levels[0]:
            MSD=a
        else:
            MSD=MSD.join(a)
    return MSD

In [90]:
def get_combined_MSD(baseline_byplate,tap_byplate, by=['Gene','dataset']):
    """
    Combines MSD datafram from baseline plates and tap plates

    input:
        - baseline_byplate: baseline data by plate
        - tap_byplate: tap data by plate
        - by: what to group by "Gene" or "dataset"
    returns:
        - combined MSD dataframe
    """
    list_baseline_MSD=calculate_MSD(extract_phenotypes(baseline_byplate), by=by)

    list_tap_MSD=calculate_MSD(extract_phenotypes(tap_byplate), by=by)

    # list_psa_MSD=calculate_MSD(extract_phenotypes(psa_byplate), by=by)

    baseline_MSD = get_MSD(list_baseline_MSD)
    
    tap_MSD = get_MSD(list_tap_MSD)
    # psa_MSD = get_MSD(list_psa_MSD)

    combined_MSD = pd.merge(baseline_MSD, tap_MSD, on=by, how='outer')

    combined_MSD=combined_MSD.rename(columns={"habit_dura":"Habituation of Response Duration",
                                         "habit_prob": "Habituation of Response Probability",
                                         "habit_speed":"Habituation of Response Speed",
                                         "habit_psa_speed":"Habituation of PSA Speed",
                                         "habit_psa_bias":"Habituation of PSA Bias",
                                         "habit_psa_aspect_ratio":"Habituation of PSA Aspect Ratio",
                                         "habit_psa_kink":"Habituation of PSA Kink",
                                         "habit_psa_curve":"Habituation of PSA Curve",
                                         "habit_psa_crab":"Habituation of PSA Crab",
                                         "init_dura": "Initial Response Duration",
                                         "init_prob": "Initial Response Probability",
                                         "init_speed": "Initial Response Speed",
                                         "init_psa_speed": "Initial PSA Speed",
                                         "init_psa_bias": "Initial PSA Bias",
                                         "init_psa_aspect_ratio": "Initial PSA Aspect Ratio",
                                         "init_psa_kink": "Initial PSA Kink",
                                         "init_psa_curve": "Initial PSA Curve",
                                         "init_psa_crab": "Initial PSA Crab",
                                         "final_dura": "Final Response Duration",
                                         "final_prob": "Final Response Probability",
                                         "final_speed": "Final Response Speed",
                                         "final_psa_speed": "Final PSA Speed",
                                         "final_psa_bias": "Final PSA Bias",
                                         "final_psa_aspect_ratio": "Final PSA Aspect Ratio",
                                         "final_psa_kink": "Final PSA Kink",
                                         "final_psa_curve": "Final PSA Curve",
                                         "final_psa_crab": "Final PSA Crab",
                                         "recovery_dura": "Spontaneous Recovery of Response Duration",
                                         "recovery_prob": "Spontaneous Recovery of Response Probability",
                                         "recovery_speed": "Spontaneous Recovery of Response Speed",
                                         "recovery_psa_speed": "Spontaneous Recovery of PSA Speed",
                                         "recovery_psa_bias": "Spontaneous Recovery of PSA Bias",
                                         "recovery_psa_aspect_ratio": "Spontaneous Recovery of PSA Aspect Ratio",
                                         "recovery_psa_kink": "Spontaneous Recovery of PSA Kink",
                                         "recovery_psa_curve": "Spontaneous Recovery of PSA Curve",
                                         "recovery_psa_crab": "Spontaneous Recovery of PSA Crab",
                                         "recov_psa_speed": "Spontaneous Recovery Stimulus of PSA Speed",
                                         "recov_psa_bias": "Spontaneous Recovery Stimulus of PSA Bias",
                                         "recov_psa_aspect_ratio": "Spontaneous Recovery Stimulus of PSA Aspect Ratio",
                                         "recov_psa_kink": "Spontaneous Recovery Stimulus of PSA Kink",
                                         "recov_psa_curve": "Spontaneous Recovery Stimulus of PSA Curve",
                                         "recov_psa_crab": "Spontaneous Recovery Stimulus of PSA Crab",
                                         "memory_retention_dura": "Memory Retention of Response Duration",
                                         "memory_retention_prob": "Memory Retention of Response Probability",
                                         "memory_retention_speed": "Memory Retention of Response Speed",
                                         "memory_retention_psa_speed": "Memory Retention of PSA Speed",
                                         "memory_retention_psa_bias": "Memory Retention of PSA Bias",
                                         "memory_retention_psa_aspect_ratio": "Memory Retention of PSA Aspect Ratio",
                                         "memory_retention_psa_kink": "Memory Retention of PSA Kink",
                                         "memory_retention_psa_curve": "Memory Retention of PSA Curve",
                                         "memory_retention_psa_crab": "Memory Retention of PSA Crab",
                                         "sensitization_psa_speed": "Sensitization of PSA Speed",
                                         "sensitization_psa_bias": "Sensitization of PSA Bias",
                                         "sensitization_psa_aspect_ratio": "Sensitization of PSA Aspect Ratio",
                                         "sensitization_psa_kink": "Sensitization of PSA Kink",
                                         "sensitization_psa_curve": "Sensitization of PSA Curve",
                                         "sensitization_psa_crab": "Sensitization of PSA Crab",
                                         "max_psa_speed": "Peak PSA Speed",
                                         "max_psa_bias": "Peak PSA Bias",
                                         "max_psa_aspect_ratio": "Peak PSA Aspect Ratio",
                                         "max_psa_kink": "Peak PSA Kink",
                                         "max_psa_curve": "Peak PSA Curve",
                                         "max_psa_crab": "Peak PSA Crab",
                                         "mean_psa_speed": "Average PSA Speed",
                                         "mean_psa_bias": "Average PSA Bias",
                                         "mean_psa_aspect_ratio": "Average PSA Aspect Ratio",
                                         "mean_psa_kink": "Average PSA Kink",
                                         "mean_psa_curve": "Average PSA Curve",
                                         "mean_psa_crab": "Average PSA Crab"})

    combined_MSD=combined_MSD.reset_index()
    combined_MSD.columns = combined_MSD.columns.to_flat_index().str.join('-')
    combined_MSD=combined_MSD.rename(columns={by+"-": by})
    combined_MSD['Screen']=Screen
    
    return combined_MSD

### 3.2.1 Gene-level MSD

In [89]:
print(combined_MSD.columns.to_list())

['Gene', 'Speed-mean', 'Speed-count', 'Speed-sem', 'Speed-ci95_hi', 'Speed-ci95_lo', 'Interval Speed-mean', 'Interval Speed-count', 'Interval Speed-sem', 'Interval Speed-ci95_hi', 'Interval Speed-ci95_lo', 'Bias-mean', 'Bias-count', 'Bias-sem', 'Bias-ci95_hi', 'Bias-ci95_lo', 'Morphwidth-mean', 'Morphwidth-count', 'Morphwidth-sem', 'Morphwidth-ci95_hi', 'Morphwidth-ci95_lo', 'Midline-mean', 'Midline-count', 'Midline-sem', 'Midline-ci95_hi', 'Midline-ci95_lo', 'Area-mean', 'Area-count', 'Area-sem', 'Area-ci95_hi', 'Area-ci95_lo', 'Angular Speed-mean', 'Angular Speed-count', 'Angular Speed-sem', 'Angular Speed-ci95_hi', 'Angular Speed-ci95_lo', 'Aspect Ratio-mean', 'Aspect Ratio-count', 'Aspect Ratio-sem', 'Aspect Ratio-ci95_hi', 'Aspect Ratio-ci95_lo', 'Kink-mean', 'Kink-count', 'Kink-sem', 'Kink-ci95_hi', 'Kink-ci95_lo', 'Curve-mean', 'Curve-count', 'Curve-sem', 'Curve-ci95_hi', 'Curve-ci95_lo', 'Crab-mean', 'Crab-count', 'Crab-sem', 'Crab-ci95_hi', 'Crab-ci95_lo', 'Pathlength-mean', 'Pathlength-count', 'Pathlength-sem', 'Pathlength-ci95_hi', 'Pathlength-ci95_lo', 'Initial Response Duration-mean', 'Initial Response Duration-count', 'Initial Response Duration-sem', 'Initial Response Duration-ci95_hi', 'Initial Response Duration-ci95_lo', 'Initial Response Probability-mean', 'Initial Response Probability-count', 'Initial Response Probability-sem', 'Initial Response Probability-ci95_hi', 'Initial Response Probability-ci95_lo', 'Initial Response Speed-mean', 'Initial Response Speed-count', 'Initial Response Speed-sem', 'Initial Response Speed-ci95_hi', 'Initial Response Speed-ci95_lo', 'init_psa_speed-mean', 'init_psa_speed-count', 'init_psa_speed-sem', 'init_psa_speed-ci95_hi', 'init_psa_speed-ci95_lo', 'init_psa_bias-mean', 'init_psa_bias-count', 'init_psa_bias-sem', 'init_psa_bias-ci95_hi', 'init_psa_bias-ci95_lo', 'init_psa_aspect_ratio-mean', 'init_psa_aspect_ratio-count', 'init_psa_aspect_ratio-sem', 'init_psa_aspect_ratio-ci95_hi', 'init_psa_aspect_ratio-ci95_lo', 'init_psa_kink-mean', 'init_psa_kink-count', 'init_psa_kink-sem', 'init_psa_kink-ci95_hi', 'init_psa_kink-ci95_lo', 'init_psa_curve-mean', 'init_psa_curve-count', 'init_psa_curve-sem', 'init_psa_curve-ci95_hi', 'init_psa_curve-ci95_lo', 'init_psa_crab-mean', 'init_psa_crab-count', 'init_psa_crab-sem', 'init_psa_crab-ci95_hi', 'init_psa_crab-ci95_lo', 'Final Response Duration-mean', 'Final Response Duration-count', 'Final Response Duration-sem', 'Final Response Duration-ci95_hi', 'Final Response Duration-ci95_lo', 'Final Response Probability-mean', 'Final Response Probability-count', 'Final Response Probability-sem', 'Final Response Probability-ci95_hi', 'Final Response Probability-ci95_lo', 'Final Response Speed-mean', 'Final Response Speed-count', 'Final Response Speed-sem', 'Final Response Speed-ci95_hi', 'Final Response Speed-ci95_lo', 'final_psa_speed-mean', 'final_psa_speed-count', 'final_psa_speed-sem', 'final_psa_speed-ci95_hi', 'final_psa_speed-ci95_lo', 'final_psa_bias-mean', 'final_psa_bias-count', 'final_psa_bias-sem', 'final_psa_bias-ci95_hi', 'final_psa_bias-ci95_lo', 'final_psa_aspect_ratio-mean', 'final_psa_aspect_ratio-count', 'final_psa_aspect_ratio-sem', 'final_psa_aspect_ratio-ci95_hi', 'final_psa_aspect_ratio-ci95_lo', 'final_psa_kink-mean', 'final_psa_kink-count', 'final_psa_kink-sem', 'final_psa_kink-ci95_hi', 'final_psa_kink-ci95_lo', 'final_psa_curve-mean', 'final_psa_curve-count', 'final_psa_curve-sem', 'final_psa_curve-ci95_hi', 'final_psa_curve-ci95_lo', 'final_psa_crab-mean', 'final_psa_crab-count', 'final_psa_crab-sem', 'final_psa_crab-ci95_hi', 'final_psa_crab-ci95_lo', 'Habituation of Response Duration-mean', 'Habituation of Response Duration-count', 'Habituation of Response Duration-sem', 'Habituation of Response Duration-ci95_hi', 'Habituation of Response Duration-ci95_lo', 'Habituation of Response Probability-mean', 'Habituation of Response Probability-count', 'Habituation of Response Probability-sem', 'Habituation of Response Probability-ci95_hi', 'Habituation of Response Probability-ci95_lo', 'Habituation of Response Speed-mean', 'Habituation of Response Speed-count', 'Habituation of Response Speed-sem', 'Habituation of Response Speed-ci95_hi', 'Habituation of Response Speed-ci95_lo', 'habit_psa_speed-mean', 'habit_psa_speed-count', 'habit_psa_speed-sem', 'habit_psa_speed-ci95_hi', 'habit_psa_speed-ci95_lo', 'habit_psa_bias-mean', 'habit_psa_bias-count', 'habit_psa_bias-sem', 'habit_psa_bias-ci95_hi', 'habit_psa_bias-ci95_lo', 'habit_psa_aspect_ratio-mean', 'habit_psa_aspect_ratio-count', 'habit_psa_aspect_ratio-sem', 'habit_psa_aspect_ratio-ci95_hi', 'habit_psa_aspect_ratio-ci95_lo', 'habit_psa_kink-mean', 'habit_psa_kink-count', 'habit_psa_kink-sem', 'habit_psa_kink-ci95_hi', 'habit_psa_kink-ci95_lo', 'habit_psa_curve-mean', 'habit_psa_curve-count', 'habit_psa_curve-sem', 'habit_psa_curve-ci95_hi', 'habit_psa_curve-ci95_lo', 'habit_psa_crab-mean', 'habit_psa_crab-count', 'habit_psa_crab-sem', 'habit_psa_crab-ci95_hi', 'habit_psa_crab-ci95_lo', 'recov_psa_speed-mean', 'recov_psa_speed-count', 'recov_psa_speed-sem', 'recov_psa_speed-ci95_hi', 'recov_psa_speed-ci95_lo', 'recov_psa_bias-mean', 'recov_psa_bias-count', 'recov_psa_bias-sem', 'recov_psa_bias-ci95_hi', 'recov_psa_bias-ci95_lo', 'recov_psa_aspect_ratio-mean', 'recov_psa_aspect_ratio-count', 'recov_psa_aspect_ratio-sem', 'recov_psa_aspect_ratio-ci95_hi', 'recov_psa_aspect_ratio-ci95_lo', 'recov_psa_kink-mean', 'recov_psa_kink-count', 'recov_psa_kink-sem', 'recov_psa_kink-ci95_hi', 'recov_psa_kink-ci95_lo', 'recov_psa_curve-mean', 'recov_psa_curve-count', 'recov_psa_curve-sem', 'recov_psa_curve-ci95_hi', 'recov_psa_curve-ci95_lo', 'recov_psa_crab-mean', 'recov_psa_crab-count', 'recov_psa_crab-sem', 'recov_psa_crab-ci95_hi', 'recov_psa_crab-ci95_lo', 'Spontaneous Recovery of Response Duration-mean', 'Spontaneous Recovery of Response Duration-count', 'Spontaneous Recovery of Response Duration-sem', 'Spontaneous Recovery of Response Duration-ci95_hi', 'Spontaneous Recovery of Response Duration-ci95_lo', 'Spontaneous Recovery of Response Probability-mean', 'Spontaneous Recovery of Response Probability-count', 'Spontaneous Recovery of Response Probability-sem', 'Spontaneous Recovery of Response Probability-ci95_hi', 'Spontaneous Recovery of Response Probability-ci95_lo', 'Spontaneous Recovery of Response Speed-mean', 'Spontaneous Recovery of Response Speed-count', 'Spontaneous Recovery of Response Speed-sem', 'Spontaneous Recovery of Response Speed-ci95_hi', 'Spontaneous Recovery of Response Speed-ci95_lo', 'recovery_psa_speed-mean', 'recovery_psa_speed-count', 'recovery_psa_speed-sem', 'recovery_psa_speed-ci95_hi', 'recovery_psa_speed-ci95_lo', 'recovery_psa_bias-mean', 'recovery_psa_bias-count', 'recovery_psa_bias-sem', 'recovery_psa_bias-ci95_hi', 'recovery_psa_bias-ci95_lo', 'recovery_psa_aspect_ratio-mean', 'recovery_psa_aspect_ratio-count', 'recovery_psa_aspect_ratio-sem', 'recovery_psa_aspect_ratio-ci95_hi', 'recovery_psa_aspect_ratio-ci95_lo', 'recovery_psa_kink-mean', 'recovery_psa_kink-count', 'recovery_psa_kink-sem', 'recovery_psa_kink-ci95_hi', 'recovery_psa_kink-ci95_lo', 'recovery_psa_curve-mean', 'recovery_psa_curve-count', 'recovery_psa_curve-sem', 'recovery_psa_curve-ci95_hi', 'recovery_psa_curve-ci95_lo', 'recovery_psa_crab-mean', 'recovery_psa_crab-count', 'recovery_psa_crab-sem', 'recovery_psa_crab-ci95_hi', 'recovery_psa_crab-ci95_lo', 'Memory Retention of Response Duration-mean', 'Memory Retention of Response Duration-count', 'Memory Retention of Response Duration-sem', 'Memory Retention of Response Duration-ci95_hi', 'Memory Retention of Response Duration-ci95_lo', 'Memory Retention of Response Probability-mean', 'Memory Retention of Response Probability-count', 'Memory Retention of Response Probability-sem', 'Memory Retention of Response Probability-ci95_hi', 'Memory Retention of Response Probability-ci95_lo', 'Memory Retention of Response Speed-mean', 'Memory Retention of Response Speed-count', 'Memory Retention of Response Speed-sem', 'Memory Retention of Response Speed-ci95_hi', 'Memory Retention of Response Speed-ci95_lo', 'memory_retention_psa_speed-mean', 'memory_retention_psa_speed-count', 'memory_retention_psa_speed-sem', 'memory_retention_psa_speed-ci95_hi', 'memory_retention_psa_speed-ci95_lo', 'memory_retention_psa_bias-mean', 'memory_retention_psa_bias-count', 'memory_retention_psa_bias-sem', 'memory_retention_psa_bias-ci95_hi', 'memory_retention_psa_bias-ci95_lo', 'memory_retention_psa_aspect_ratio-mean', 'memory_retention_psa_aspect_ratio-count', 'memory_retention_psa_aspect_ratio-sem', 'memory_retention_psa_aspect_ratio-ci95_hi', 'memory_retention_psa_aspect_ratio-ci95_lo', 'memory_retention_psa_kink-mean', 'memory_retention_psa_kink-count', 'memory_retention_psa_kink-sem', 'memory_retention_psa_kink-ci95_hi', 'memory_retention_psa_kink-ci95_lo', 'memory_retention_psa_curve-mean', 'memory_retention_psa_curve-count', 'memory_retention_psa_curve-sem', 'memory_retention_psa_curve-ci95_hi', 'memory_retention_psa_curve-ci95_lo', 'memory_retention_psa_crab-mean', 'memory_retention_psa_crab-count', 'memory_retention_psa_crab-sem', 'memory_retention_psa_crab-ci95_hi', 'memory_retention_psa_crab-ci95_lo', 'max_psa_speed-mean', 'max_psa_speed-count', 'max_psa_speed-sem', 'max_psa_speed-ci95_hi', 'max_psa_speed-ci95_lo', 'max_psa_bias-mean', 'max_psa_bias-count', 'max_psa_bias-sem', 'max_psa_bias-ci95_hi', 'max_psa_bias-ci95_lo', 'max_psa_aspect_ratio-mean', 'max_psa_aspect_ratio-count', 'max_psa_aspect_ratio-sem', 'max_psa_aspect_ratio-ci95_hi', 'max_psa_aspect_ratio-ci95_lo', 'max_psa_kink-mean', 'max_psa_kink-count', 'max_psa_kink-sem', 'max_psa_kink-ci95_hi', 'max_psa_kink-ci95_lo', 'max_psa_curve-mean', 'max_psa_curve-count', 'max_psa_curve-sem', 'max_psa_curve-ci95_hi', 'max_psa_curve-ci95_lo', 'max_psa_crab-mean', 'max_psa_crab-count', 'max_psa_crab-sem', 'max_psa_crab-ci95_hi', 'max_psa_crab-ci95_lo', 'mean_dura-mean', 'mean_dura-count', 'mean_dura-sem', 'mean_dura-ci95_hi', 'mean_dura-ci95_lo', 'mean_prob-mean', 'mean_prob-count', 'mean_prob-sem', 'mean_prob-ci95_hi', 'mean_prob-ci95_lo', 'mean_speed-mean', 'mean_speed-count', 'mean_speed-sem', 'mean_speed-ci95_hi', 'mean_speed-ci95_lo', 'mean_psa_speed-mean', 'mean_psa_speed-count', 'mean_psa_speed-sem', 'mean_psa_speed-ci95_hi', 'mean_psa_speed-ci95_lo', 'mean_psa_bias-mean', 'mean_psa_bias-count', 'mean_psa_bias-sem', 'mean_psa_bias-ci95_hi', 'mean_psa_bias-ci95_lo', 'mean_psa_aspect_ratio-mean', 'mean_psa_aspect_ratio-count', 'mean_psa_aspect_ratio-sem', 'mean_psa_aspect_ratio-ci95_hi', 'mean_psa_aspect_ratio-ci95_lo', 'mean_psa_kink-mean', 'mean_psa_kink-count', 'mean_psa_kink-sem', 'mean_psa_kink-ci95_hi', 'mean_psa_kink-ci95_lo', 'mean_psa_curve-mean', 'mean_psa_curve-count', 'mean_psa_curve-sem', 'mean_psa_curve-ci95_hi', 'mean_psa_curve-ci95_lo', 'mean_psa_crab-mean', 'mean_psa_crab-count', 'mean_psa_crab-sem', 'mean_psa_crab-ci95_hi', 'mean_psa_crab-ci95_lo', 'sensitization_psa_speed-mean', 'sensitization_psa_speed-count', 'sensitization_psa_speed-sem', 'sensitization_psa_speed-ci95_hi', 'sensitization_psa_speed-ci95_lo', 'sensitization_psa_bias-mean', 'sensitization_psa_bias-count', 'sensitization_psa_bias-sem', 'sensitization_psa_bias-ci95_hi', 'sensitization_psa_bias-ci95_lo', 'sensitization_psa_aspect_ratio-mean', 'sensitization_psa_aspect_ratio-count', 'sensitization_psa_aspect_ratio-sem', 'sensitization_psa_aspect_ratio-ci95_hi', 'sensitization_psa_aspect_ratio-ci95_lo', 'sensitization_psa_kink-mean', 'sensitization_psa_kink-count', 'sensitization_psa_kink-sem', 'sensitization_psa_kink-ci95_hi', 'sensitization_psa_kink-ci95_lo', 'sensitization_psa_curve-mean', 'sensitization_psa_curve-count', 'sensitization_psa_curve-sem', 'sensitization_psa_curve-ci95_hi', 'sensitization_psa_curve-ci95_lo', 'sensitization_psa_crab-mean', 'sensitization_psa_crab-count', 'sensitization_psa_crab-sem', 'sensitization_psa_crab-ci95_hi', 'sensitization_psa_crab-ci95_lo', 'Screen']

In [91]:
combined_MSD=get_combined_MSD(baseline_output_byplate,
                              tap_data_byplate, 
                            #   psa_data_byplate,
                              by='Gene')

combined_MSD.head()

,Gene,Speed-mean,Speed-count,Speed-sem,Speed-ci95_hi,Speed-ci95_lo,Interval Speed-mean,Interval Speed-count,Interval Speed-sem,Interval Speed-ci95_hi,...,Sensitization of PSA Curve-count,Sensitization of PSA Curve-sem,Sensitization of PSA Curve-ci95_hi,Sensitization of PSA Curve-ci95_lo,Sensitization of PSA Crab-mean,Sensitization of PSA Crab-count,Sensitization of PSA Crab-sem,Sensitization of PSA Crab-ci95_hi,Sensitization of PSA Crab-ci95_lo,Screen
0,AMshABLATE,-0.041748,5,0.001839,-0.036643,-0.046853,-0.046065,5,0.001349,-0.042320,...,5,0.167816,0.550823,-0.381041,0.002851,5,0.000922,0.005411,0.000291,Glia_Genes_Screen
1,N2,0.000000,75,0.002216,0.004416,-0.004416,0.000000,75,0.001907,0.003800,...,74,0.041432,0.082574,-0.082574,0.000000,74,0.000335,0.000668,-0.000668,Glia_Genes_Screen
2,ced-10,-0.032393,12,0.002271,-0.027395,-0.037392,-0.039954,12,0.002340,-0.034804,...,12,1.356572,9.513403,3.541815,0.003921,12,0.002513,0.009453,-0.001611,Glia_Genes_Screen
3,ced-5,-0.029867,9,0.006192,-0.015588,-0.044147,-0.041997,9,0.005558,-0.029180,...,6,0.647036,2.897139,-0.429378,-0.006097,6,0.000560,-0.004657,-0.007537,Glia_Genes_Screen
4,delm-1,-0.001439,10,0.006662,0.013633,-0.016511,-0.008167,10,0.011252,0.017287,...,9,0.946576,4.223302,-0.142313,-0.001757,9,0.001135,0.000860,-0.004373,Glia_Genes_Screen

### 3.2.2 Allele-level SMD

In [92]:
allele_combined_MSD=get_combined_MSD(baseline_output_allele_byplate,
                                     tap_data_allele_byplate, 
                                    #  psa_data_allele_byplate,
                                     by='dataset')

allele_combined_MSD.head()

,dataset,Speed-mean,Speed-count,Speed-sem,Speed-ci95_hi,Speed-ci95_lo,Interval Speed-mean,Interval Speed-count,Interval Speed-sem,Interval Speed-ci95_hi,...,Sensitization of PSA Curve-count,Sensitization of PSA Curve-sem,Sensitization of PSA Curve-ci95_hi,Sensitization of PSA Curve-ci95_lo,Sensitization of PSA Crab-mean,Sensitization of PSA Crab-count,Sensitization of PSA Crab-sem,Sensitization of PSA Crab-ci95_hi,Sensitization of PSA Crab-ci95_lo,Screen
0,AMshABLATE_nsIs109,-0.041748,5,0.001839,-0.036643,-0.046853,-0.046065,5,0.001349,-0.042320,...,5,0.167816,0.550823,-0.381041,0.002851,5,0.000922,0.005411,0.000291,Glia_Genes_Screen
1,N2,0.000000,75,0.002216,0.004416,-0.004416,0.000000,75,0.001907,0.003800,...,74,0.041432,0.082574,-0.082574,0.000000,74,0.000335,0.000668,-0.000668,Glia_Genes_Screen
2,ced-10_n3246,-0.032393,12,0.002271,-0.027395,-0.037392,-0.039954,12,0.002340,-0.034804,...,12,1.356572,9.513403,3.541815,0.003921,12,0.002513,0.009453,-0.001611,Glia_Genes_Screen
3,ced-5_n2002,-0.029867,9,0.006192,-0.015588,-0.044147,-0.041997,9,0.005558,-0.029180,...,6,0.647036,2.897139,-0.429378,-0.006097,6,0.000560,-0.004657,-0.007537,Glia_Genes_Screen
4,delm-1_ok1226,-0.001439,10,0.006662,0.013633,-0.016511,-0.008167,10,0.011252,0.017287,...,9,0.946576,4.223302,-0.142313,-0.001757,9,0.001135,0.000860,-0.004373,Glia_Genes_Screen

## 3.3 T-Stat analysis

In [103]:
def baseline_metrics(by=["Gene","dataset"]):
    """
    Create a list of empty dataframe and list of metrics for baseline analysis

    input:
        by (list): what to group by "Gene" or "dataset"
        
    returns:
        list_baseline_Tstats: dataframes to store t-statistics
        list_baseline_metrics: dataframes to store metic names
    """
    PD_baseline_instantspeed_T=pd.DataFrame(columns = [by,"Speed", "Speed p-value"])
    # PD_baseline_intspeed_T=pd.DataFrame(columns = [by,"Interval Speed"])
    PD_baseline_bias_T=pd.DataFrame(columns = [by,"Bias", "Bias p-value"])
    PD_baseline_morphwidth_T=pd.DataFrame(columns = [by,"Morphwidth", "Morphwidth p-value"])
    PD_baseline_midline_T=pd.DataFrame(columns = [by,"Midline", "Midline p-value"])
    PD_baseline_area_T=pd.DataFrame(columns = [by,"Area", "Area p-value"])
    PD_baseline_angularspeed_T=pd.DataFrame(columns = [by,"Angular Speed", "Angular Speed p-value"])
    PD_baseline_aspectratio_T=pd.DataFrame(columns = [by,"Aspect Ratio", "Aspect Ratio p-value"])
    PD_baseline_kink_T=pd.DataFrame(columns = [by,"Kink", "Kink p-value"])
    PD_baseline_curve_T=pd.DataFrame(columns = [by,"Curve", "Curve p-value"])
    PD_baseline_crab_T=pd.DataFrame(columns = [by,"Crab", "Crab p-value"])
    PD_baseline_pathlength_T=pd.DataFrame(columns = [by,"Pathlength", "Pathlength p-value"])

    list_baseline_Tstats=[PD_baseline_instantspeed_T,
                        # PD_baseline_intspeed_T,
                        PD_baseline_bias_T,
                        PD_baseline_morphwidth_T,
                        PD_baseline_midline_T,
                        PD_baseline_area_T,
                        PD_baseline_angularspeed_T,
                        PD_baseline_aspectratio_T,
                        PD_baseline_kink_T,
                        PD_baseline_curve_T,
                        PD_baseline_crab_T,
                        PD_baseline_pathlength_T]

    list_baseline_metrics=["Speed",
                        # "Interval Speed",
                        "Bias",
                        "Morphwidth",
                        "Midline",
                        "Area",
                        "Angular Speed",
                        "Aspect Ratio",
                        "Kink",
                        "Curve",
                        "Crab",
                        "Pathlength"]
    
    return list_baseline_Tstats, list_baseline_metrics

In [ ]:
def tap_metrics(by=["Gene","dataset"]):
    """
    Create a list of empty dataframes and list of metrics for tap analysis

    input:
        by (list): what to group by "Gene" or "dataset"
        
    returns:
        list_tap_Tstats: dataframes to store t-statistics
        list_tap_metrics: dataframes to store metic names
    """
    recovery_dura=pd.DataFrame(columns = [by,"Spontaneous Recovery of Response Duration", "Spontaneous Recovery of Response Duration p-value"])
    recovery_prob=pd.DataFrame(columns = [by,"Spontaneous Recovery of Response Probability", "Spontaneous Recovery of Response Probability p-value"])
    recovery_speed=pd.DataFrame(columns = [by,"Spontaneous Recovery of Response Speed", "Spontaneous Recovery of Response Speed p-value"])
    memory_retention_dura=pd.DataFrame(columns = [by,"Memory Retention of Response Duration", "Memory Retention of Response Duration p-value"])
    memory_retention_prob=pd.DataFrame(columns = [by,"Memory Retention of Response Probability", "Memory Retention of Response Probability p-value"])
    memory_retention_speed=pd.DataFrame(columns = [by,"Memory Retention of Response Speed", "Memory Retention of Response Speed p-value"])
    init_dura=pd.DataFrame(columns = [by,"Initial Response Duration", "Initial Response Duration p-value"])
    init_prob=pd.DataFrame(columns = [by,"Initial Response Probability", "Initial Response Probability p-value"])
    init_speed=pd.DataFrame(columns = [by,"Initial Response Speed", "Initial Response Speed p-value"])
    final_dura=pd.DataFrame(columns = [by,"Final Response Duration", "Final Response Duration p-value"])
    final_prob=pd.DataFrame(columns = [by,"Final Response Probability", "Final Response Probability p-value"])
    final_speed=pd.DataFrame(columns = [by,"Final Response Speed", "Final Response Speed p-value"])
    hab_dura=pd.DataFrame(columns = [by,"Habituation of Response Duration", "Habituation of Response Duration p-value"])
    hab_prob=pd.DataFrame(columns = [by,"Habituation of Response Probability", "Habituation of Response Probability p-value"])
    hab_speed=pd.DataFrame(columns = [by,"Habituation of Response Speed", "Habituation of Response Speed p-value"])

    psa_initial_speed = pd.DataFrame(columns=[by,"Initial PSA Speed", "Initial PSA Speed p-value"])
    psa_final_speed = pd.DataFrame(columns=[by,"Final PSA Speed", "Final PSA Speed p-value"])
    psa_recovery_speed = pd.DataFrame(columns=[by,"Recovery PSA Speed", "Recovery PSA Speed p-value"])
    psa_peak_speed = pd.DataFrame(columns=[by,"Peak PSA Speed", "Peak PSA Speed p-value"])
    # psa_peak_tap_speed = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Speed"])
    psa_avg_speed = pd.DataFrame(columns=[by,"Average PSA Speed", "Average PSA Speed p-value"])
    psa_sensitization_speed = pd.DataFrame(columns=[by,"Sensitization of PSA Speed", "Sensitization of PSA Speed p-value"])
    psa_habituation_speed = pd.DataFrame(columns=[by,"Habituation of PSA Speed", "Habituation of PSA Speed p-value"])
    psa_spontaneous_recovery_speed = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Speed", "Spontaneous Recovery of PSA Speed p-value"])
    psa_memory_retention_speed = pd.DataFrame(columns=[by,"Memory Retention of PSA Speed", "Memory Retention of PSA Speed p-value"])
    # psa_initial_to_peak_speed = pd.DataFrame(columns=[by,"Initial_to_peak PSA Speed"])
    # psa_peak_to_recovery_speed = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Speed"])

    psa_initial_bias = pd.DataFrame(columns=[by,"Initial PSA Bias", "Initial PSA Bias p-value"])
    psa_final_bias = pd.DataFrame(columns=[by,"Final PSA Bias", "Final PSA Bias p-value"])
    psa_recovery_bias = pd.DataFrame(columns=[by,"Recovery PSA Bias", "Recovery PSA Bias p-value"])
    psa_peak_bias = pd.DataFrame(columns=[by,"Peak PSA Bias", "Peak PSA Bias p-value"])
    # psa_peak_tap_bias = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Bias"])
    psa_avg_bias = pd.DataFrame(columns=[by,"Average PSA Bias", "Average PSA Bias p-value"])
    psa_sensitization_bias = pd.DataFrame(columns=[by,"Sensitization of PSA Bias", "Sensitization of PSA Bias p-value"])
    psa_habituation_bias = pd.DataFrame(columns=[by,"Habituation of PSA Bias", "Habituation of PSA Bias p-value"])
    psa_spontaneous_recovery_bias = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Bias", "Spontaneous Recovery of PSA Bias p-value"])
    psa_memory_retention_bias = pd.DataFrame(columns=[by,"Memory Retention of PSA Bias", "Memory Retention of PSA Bias p-value"])

    psa_initial_aspect = pd.DataFrame(columns=[by,"Initial PSA Aspect Ratio", "Initial PSA Aspect Ratio p-value"])
    psa_final_aspect = pd.DataFrame(columns=[by,"Final PSA Aspect Ratio", "Final PSA Aspect Ratio p-value"])
    psa_recovery_aspect = pd.DataFrame(columns=[by,"Recovery PSA Aspect Ratio", "Recovery PSA Aspect Ratio p-value"])
    psa_peak_aspect = pd.DataFrame(columns=[by,"Peak PSA Aspect Ratio", "Peak PSA Aspect Ratio p-value"])
    # psa_peak_tap_aspect = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Aspect Ratio"])
    psa_avg_aspect = pd.DataFrame(columns=[by,"Average PSA Aspect Ratio", "Average PSA Aspect Ratio p-value"])
    psa_sensitization_aspect = pd.DataFrame(columns=[by,"Sensitization of PSA Aspect Ratio", "Sensitization of PSA Aspect Ratio p-value"])
    psa_habituation_aspect = pd.DataFrame(columns=[by,"Habituation of PSA Aspect Ratio", "Habituation of PSA Aspect Ratio p-value"])
    psa_spontaneous_recovery_aspect = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Aspect Ratio", "Spontaneous Recovery of PSA Aspect Ratio p-value"])
    psa_memory_retention_aspect = pd.DataFrame(columns=[by,"Memory Retention of PSA Aspect Ratio", "Memory Retention of PSA Aspect Ratio p-value"])
    # psa_initial_to_peak_aspect = pd.DataFrame(columns=[by,"Initial_to_peak PSA Aspect Ratio"])
    # psa_peak_to_recovery_aspect = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Aspect Ratio"])

    psa_initial_kink = pd.DataFrame(columns=[by,"Initial PSA Kink", "Initial PSA Kink p-value"])
    psa_final_kink = pd.DataFrame(columns=[by,"Final PSA Kink", "Final PSA Kink p-value"])
    psa_recovery_kink = pd.DataFrame(columns=[by,"Recovery PSA Kink", "Recovery PSA Kink p-value"])
    psa_peak_kink = pd.DataFrame(columns=[by,"Peak PSA Kink", "Peak PSA Kink p-value"])
    # psa_peak_tap_kink = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Kink"])
    psa_avg_kink = pd.DataFrame(columns=[by,"Average PSA Kink", "Average PSA Kink p-value"])
    psa_sensitization_kink = pd.DataFrame(columns=[by,"Sensitization of PSA Kink", "Sensitization of PSA Kink p-value"])
    psa_habituation_kink = pd.DataFrame(columns=[by,"Habituation of PSA Kink", "Habituation of PSA Kink p-value"])
    psa_spontaneous_recovery_kink = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Kink", "Spontaneous Recovery of PSA Kink p-value"])
    psa_memory_retention_kink = pd.DataFrame(columns=[by,"Memory Retention of PSA Kink", "Memory Retention of PSA Kink p-value"])
    # psa_initial_to_peak_kink = pd.DataFrame(columns=[by,"Initial_to_peak PSA Kink"])
    # psa_peak_to_recovery_kink = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Kink"])

    psa_initial_curve = pd.DataFrame(columns=[by,"Initial PSA Curve", "Initial PSA Curve p-value"])
    psa_final_curve = pd.DataFrame(columns=[by,"Final PSA Curve", "Final PSA Curve p-value"])
    psa_recovery_curve = pd.DataFrame(columns=[by,"Recovery PSA Curve", "Recovery PSA Curve p-value"])
    psa_peak_curve = pd.DataFrame(columns=[by,"Peak PSA Curve", "Peak PSA Curve p-value"])
    # psa_peak_tap_curve = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Curve"])
    psa_avg_curve = pd.DataFrame(columns=[by,"Average PSA Curve", "Average PSA Curve p-value"])
    psa_sensitization_curve = pd.DataFrame(columns=[by,"Sensitization of PSA Curve", "Sensitization of PSA Curve p-value"])
    psa_habituation_curve = pd.DataFrame(columns=[by,"Habituation of PSA Curve", "Habituation of PSA Curve p-value"])
    psa_spontaneous_recovery_curve = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Curve", "Spontaneous Recovery of PSA Curve p-value"])
    psa_memory_retention_curve = pd.DataFrame(columns=[by,"Memory Retention of PSA Curve", "Memory Retention of PSA Curve p-value"])
    # psa_initial_to_peak_curve = pd.DataFrame(columns=[by,"Initial_to_peak PSA Curve"])
    # psa_peak_to_recovery_curve = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Curve"])

    psa_initial_crab = pd.DataFrame(columns=[by,"Initial PSA Crab", "Initial PSA Crab p-value"])
    psa_final_crab = pd.DataFrame(columns=[by,"Final PSA Crab", "Final PSA Crab p-value"])
    psa_recovery_crab = pd.DataFrame(columns=[by,"Recovery PSA Crab", "Recovery PSA Crab p-value"])
    psa_peak_crab = pd.DataFrame(columns=[by,"Peak PSA Crab", "Peak PSA Crab p-value"])
    # psa_peak_tap_crab = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Crab"])
    psa_avg_crab = pd.DataFrame(columns=[by,"Average PSA Crab", "Average PSA Crab p-value"])
    psa_sensitization_crab = pd.DataFrame(columns=[by,"Sensitization of PSA Crab", "Sensitization of PSA Crab p-value"])
    psa_habituation_crab = pd.DataFrame(columns=[by,"Habituation of PSA Crab", "Habituation of PSA Crab p-value"])
    psa_spontaneous_recovery_crab = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Crab", "Spontaneous Recovery of PSA Crab p-value"])
    psa_memory_retention_crab = pd.DataFrame(columns=[by,"Memory Retention of PSA Crab", "Memory Retention of PSA Crab p-value"])
    
    list_tap_Tstats = [recovery_dura,
                    recovery_prob,
                    recovery_speed,
                    memory_retention_dura,
                    memory_retention_prob,
                    memory_retention_speed,
                    init_dura,
                    init_prob,
                    init_speed,
                    final_dura,
                    final_prob,
                    final_speed,
                    hab_dura,
                    hab_prob,
                    hab_speed,
                    psa_initial_speed,
                    psa_final_speed,
                    psa_recovery_speed,
                    psa_peak_speed,
                    # psa_peak_tap_speed,
                    psa_avg_speed,
                    psa_sensitization_speed,
                    psa_habituation_speed,
                    psa_spontaneous_recovery_speed,
                    psa_memory_retention_speed,
                    # psa_initial_to_peak_speed,
                    # psa_peak_to_recovery_speed,
                    psa_initial_bias,
                    psa_final_bias,
                    psa_recovery_bias,
                    psa_peak_bias,
                    # psa_peak_tap_bias,
                    psa_avg_bias,
                    psa_sensitization_bias,
                    psa_habituation_bias,
                    psa_spontaneous_recovery_bias,
                    psa_memory_retention_bias,
                    psa_initial_aspect,
                    psa_final_aspect,
                    psa_recovery_aspect,
                    psa_peak_aspect,
                    # psa_peak_tap_aspect,
                    psa_avg_aspect,
                    psa_sensitization_aspect,
                    psa_habituation_aspect,
                    psa_spontaneous_recovery_aspect,
                    psa_memory_retention_aspect,
                    # psa_initial_to_peak_aspect,
                    # psa_peak_to_recovery_aspect,
                    psa_initial_kink,
                    psa_final_kink,
                    psa_recovery_kink,
                    psa_peak_kink,
                    # psa_peak_tap_kink,
                    psa_avg_kink,
                    psa_sensitization_kink,
                    psa_habituation_kink,
                    psa_spontaneous_recovery_kink,
                    psa_memory_retention_kink,
                    # psa_initial_to_peak_kink,
                    # psa_peak_to_recovery_kink,
                    psa_initial_curve,
                    psa_final_curve,
                    psa_recovery_curve,
                    psa_peak_curve,
                    # psa_peak_tap_curve,
                    psa_avg_curve,
                    psa_sensitization_curve,
                    psa_habituation_curve,
                    psa_spontaneous_recovery_curve,
                    psa_memory_retention_curve,
                    # psa_initial_to_peak_curve,
                    # psa_peak_to_recovery_curve,
                    psa_initial_crab,
                    psa_final_crab,
                    psa_recovery_crab,
                    psa_peak_crab,
                    # psa_peak_tap_crab,
                    psa_avg_crab,
                    psa_sensitization_crab,
                    psa_habituation_crab,
                    psa_spontaneous_recovery_crab,
                    psa_memory_retention_crab]
    
    list_tap_metrics = ["recovery_dura",
                        "recovery_prob",
                        "recovery_speed",

                        "memory_retention_dura",
                        "memory_retention_prob",
                        "memory_retention_speed",

                        "init_dura",
                        "init_prob",
                        "init_speed",

                        "final_dura",
                        "final_prob",
                        "final_speed",
                        
                        "habit_dura",
                        "habit_prob",
                        "habit_speed",

                        "init_psa_speed",
                        "final_psa_speed",
                        "recov_psa_speed",
                        "max_psa_speed",
                        # "psa_peak_tap_speed",
                        "mean_psa_speed",
                        "sensitization_psa_speed",
                        "habit_psa_speed",
                        "recovery_psa_speed",
                        "memory_retention_psa_speed",
                        # "psa_initial_to_peak_speed",
                        # "psa_peak_to_recovery_speed",

                        "init_psa_bias",
                        "final_psa_bias",
                        "recov_psa_bias",
                        "max_psa_bias",
                        # "psa_peak_tap_bias",
                        "mean_psa_bias",
                        "sensitization_psa_bias",
                        "habit_psa_bias",
                        "recovery_psa_bias",
                        "memory_retention_psa_bias",

                        "init_psa_aspect_ratio",
                        "final_psa_aspect_ratio",
                        "recov_psa_aspect_ratio",
                        "max_psa_aspect_ratio",
                        # "psa_peak_tap_aspect_ratio",
                        "mean_psa_aspect_ratio",
                        "sensitization_psa_aspect_ratio",
                        "habit_psa_aspect_ratio",
                        "recovery_psa_aspect_ratio",
                        "memory_retention_psa_aspect_ratio",
                        # "psa_initial_to_peak_aspect_ratio",
                        # "psa_peak_to_recovery_aspect_ratio",

                        "init_psa_kink",
                        "final_psa_kink",
                        "recov_psa_kink",
                        "max_psa_kink",
                        # "psa_peak_tap_kink",
                        "mean_psa_kink",
                        "sensitization_psa_kink",
                        "habit_psa_kink",
                        "recovery_psa_kink",
                        "memory_retention_psa_kink",
                        # "psa_initial_to_peak_kink",
                        # "psa_peak_to_recovery_kink",

                        "init_psa_curve",
                        "final_psa_curve",
                        "recov_psa_curve",
                        "max_psa_curve",
                        # "psa_peak_tap_curve",
                        "mean_psa_curve",
                        "sensitization_psa_curve",
                        "habit_psa_curve",
                        "recovery_psa_curve",
                        "memory_retention_psa_curve",
                        # "psa_initial_to_peak_curve",
                        # "psa_peak_to_recovery_curve",

                        "init_psa_crab",
                        "final_psa_crab",
                        "recov_psa_crab",
                        "max_psa_crab",
                        # "psa_peak_tap_crab",
                        "mean_psa_crab",
                        "sensitization_psa_crab",
                        "habit_psa_crab",
                        "recovery_psa_crab",
                        "memory_retention_psa_crab"]
    
    return list_tap_Tstats, list_tap_metrics

In [121]:
print(tap_data.columns.to_list())

['dataset', 'Gene', 'Allele', 'Date', 'Plate_id', 'plate', 'Screen', 'init_dura', 'init_prob', 'init_speed', 'init_psa_speed', 'init_psa_bias', 'init_psa_aspect_ratio', 'init_psa_kink', 'init_psa_curve', 'init_psa_crab', 'final_dura', 'final_prob', 'final_speed', 'final_psa_speed', 'final_psa_bias', 'final_psa_aspect_ratio', 'final_psa_kink', 'final_psa_curve', 'final_psa_crab', 'habit_dura', 'habit_prob', 'habit_speed', 'habit_psa_speed', 'habit_psa_bias', 'habit_psa_aspect_ratio', 'habit_psa_kink', 'habit_psa_curve', 'habit_psa_crab', 'taps', 'time', 'recov_dura', 'dist', 'recov_prob', 'recov_speed', 'recov_psa_speed', 'recov_psa_bias', 'recov_psa_aspect_ratio', 'recov_psa_kink', 'recov_psa_curve', 'recov_psa_crab', 'recovery_dura', 'recovery_prob', 'recovery_speed', 'recovery_psa_speed', 'recovery_psa_bias', 'recovery_psa_aspect_ratio', 'recovery_psa_kink', 'recovery_psa_curve', 'recovery_psa_crab', 'memory_retention_dura', 'memory_retention_prob', 'memory_retention_speed', 'memory_retention_psa_speed', 'memory_retention_psa_bias', 'memory_retention_psa_aspect_ratio', 'memory_retention_psa_kink', 'memory_retention_psa_curve', 'memory_retention_psa_crab', 'max_psa_speed', 'max_psa_bias', 'max_psa_aspect_ratio', 'max_psa_kink', 'max_psa_curve', 'max_psa_crab', 'mean_dura', 'mean_prob', 'mean_speed', 'mean_psa_speed', 'mean_psa_bias', 'mean_psa_aspect_ratio', 'mean_psa_kink', 'mean_psa_curve', 'mean_psa_crab', 'sensitization_psa_speed', 'sensitization_psa_bias', 'sensitization_psa_aspect_ratio', 'sensitization_psa_kink', 'sensitization_psa_curve', 'sensitization_psa_crab']

In [ ]:
# def psa_metrics(by=["Gene", "dataset"]):
#     """
#     Create a list of empty dataframes and list of metric names for PSA summary analysis.

#     input:
#         by (list): what to group by ("Gene" or "dataset")

#     returns:
#         list_psa_Tstats: list of empty DataFrames for t-statistics
#         list_psa_metrics: list of metric names (short strings)
#     """


#     psa_initial_speed = pd.DataFrame(columns=[by,"Initial PSA Speed"])
#     psa_final_speed = pd.DataFrame(columns=[by,"Final PSA Speed"])
#     psa_recovery_speed = pd.DataFrame(columns=[by,"Recovery PSA Speed"])
#     psa_peak_speed = pd.DataFrame(columns=[by,"Peak PSA Speed"])
#     # psa_peak_tap_speed = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Speed"])
#     psa_avg_speed = pd.DataFrame(columns=[by,"Average PSA Speed"])
#     psa_sensitization_speed = pd.DataFrame(columns=[by,"Sensitization of PSA Speed"])
#     psa_habituation_speed = pd.DataFrame(columns=[by,"Habituation of PSA Speed"])
#     psa_spontaneous_recovery_speed = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Speed"])
#     psa_memory_retention_speed = pd.DataFrame(columns=[by,"Memory Retention of PSA Speed"])
#     # psa_initial_to_peak_speed = pd.DataFrame(columns=[by,"Initial_to_peak PSA Speed"])
#     # psa_peak_to_recovery_speed = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Speed"])

#     psa_initial_bias = pd.DataFrame(columns=[by,"Initial PSA Bias"])
#     psa_final_bias = pd.DataFrame(columns=[by,"Final PSA Bias"])
#     psa_recovery_bias = pd.DataFrame(columns=[by,"Recovery PSA Bias"])
#     psa_peak_bias = pd.DataFrame(columns=[by,"Peak PSA Bias"])
#     # psa_peak_tap_bias = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Bias"])
#     psa_avg_bias = pd.DataFrame(columns=[by,"Average PSA Bias"])
#     psa_sensitization_bias = pd.DataFrame(columns=[by,"Sensitization of PSA Bias"])
#     psa_habituation_bias = pd.DataFrame(columns=[by,"Habituation of PSA Bias"])
#     psa_spontaneous_recovery_bias = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Bias"])
#     psa_memory_retention_bias = pd.DataFrame(columns=[by,"Memory Retention of PSA Bias"])
#     # psa_initial_to_peak_bias = pd.DataFrame(columns=[by,"Initial_to_peak PSA Bias"])
#     # psa_peak_to_recovery_bias = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Bias"])

#     # psa_initial_ang_speed = pd.DataFrame(columns=[by,"Initial PSA Angular Speed"])
#     # psa_final_ang_speed = pd.DataFrame(columns=[by,"Final PSA Angular Speed"])
#     # psa_recovery_ang_speed = pd.DataFrame(columns=[by,"Recovery PSA Angular Speed"])
#     # psa_peak_ang_speed = pd.DataFrame(columns=[by,"Peak PSA Angular Speed"])
#     # # psa_peak_tap_ang_speed = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Angular Speed"])
#     # psa_avg_ang_speed = pd.DataFrame(columns=[by,"Average PSA Angular Speed"])
#     # psa_sensitization_ang_speed = pd.DataFrame(columns=[by,"Sensitization of PSA Angular Speed"])
#     # psa_habituation_ang_speed = pd.DataFrame(columns=[by,"Habituation of PSA Angular Speed"])
#     # psa_spontaneous_recovery_ang_speed = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Angular Speed"])
#     # psa_memory_retention_ang_speed = pd.DataFrame(columns=[by,"Memory Retention of PSA Angular Speed"])
#     # # psa_initial_to_peak_ang_speed = pd.DataFrame(columns=[by,"Initial_to_peak PSA Angular Speed"])
#     # # psa_peak_to_recovery_ang_speed = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Angular Speed"])

#     psa_initial_aspect = pd.DataFrame(columns=[by,"Initial PSA Aspect Ratio"])
#     psa_final_aspect = pd.DataFrame(columns=[by,"Final PSA Aspect Ratio"])
#     psa_recovery_aspect = pd.DataFrame(columns=[by,"Recovery PSA Aspect Ratio"])
#     psa_peak_aspect = pd.DataFrame(columns=[by,"Peak PSA Aspect Ratio"])
#     # psa_peak_tap_aspect = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Aspect Ratio"])
#     psa_avg_aspect = pd.DataFrame(columns=[by,"Average PSA Aspect Ratio"])
#     psa_sensitization_aspect = pd.DataFrame(columns=[by,"Sensitization of PSA Aspect Ratio"])
#     psa_habituation_aspect = pd.DataFrame(columns=[by,"Habituation of PSA Aspect Ratio"])
#     psa_spontaneous_recovery_aspect = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Aspect Ratio"])
#     psa_memory_retention_aspect = pd.DataFrame(columns=[by,"Memory Retention of PSA Aspect Ratio"])
#     # psa_initial_to_peak_aspect = pd.DataFrame(columns=[by,"Initial_to_peak PSA Aspect Ratio"])
#     # psa_peak_to_recovery_aspect = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Aspect Ratio"])

#     psa_initial_kink = pd.DataFrame(columns=[by,"Initial PSA Kink"])
#     psa_final_kink = pd.DataFrame(columns=[by,"Final PSA Kink"])
#     psa_recovery_kink = pd.DataFrame(columns=[by,"Recovery PSA Kink"])
#     psa_peak_kink = pd.DataFrame(columns=[by,"Peak PSA Kink"])
#     # psa_peak_tap_kink = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Kink"])
#     psa_avg_kink = pd.DataFrame(columns=[by,"Average PSA Kink"])
#     psa_sensitization_kink = pd.DataFrame(columns=[by,"Sensitization of PSA Kink"])
#     psa_habituation_kink = pd.DataFrame(columns=[by,"Habituation of PSA Kink"])
#     psa_spontaneous_recovery_kink = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Kink"])
#     psa_memory_retention_kink = pd.DataFrame(columns=[by,"Memory Retention of PSA Kink"])
#     # psa_initial_to_peak_kink = pd.DataFrame(columns=[by,"Initial_to_peak PSA Kink"])
#     # psa_peak_to_recovery_kink = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Kink"])

#     psa_initial_curve = pd.DataFrame(columns=[by,"Initial PSA Curve"])
#     psa_final_curve = pd.DataFrame(columns=[by,"Final PSA Curve"])
#     psa_recovery_curve = pd.DataFrame(columns=[by,"Recovery PSA Curve"])
#     psa_peak_curve = pd.DataFrame(columns=[by,"Peak PSA Curve"])
#     # psa_peak_tap_curve = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Curve"])
#     psa_avg_curve = pd.DataFrame(columns=[by,"Average PSA Curve"])
#     psa_sensitization_curve = pd.DataFrame(columns=[by,"Sensitization of PSA Curve"])
#     psa_habituation_curve = pd.DataFrame(columns=[by,"Habituation of PSA Curve"])
#     psa_spontaneous_recovery_curve = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Curve"])
#     psa_memory_retention_curve = pd.DataFrame(columns=[by,"Memory Retention of PSA Curve"])
#     # psa_initial_to_peak_curve = pd.DataFrame(columns=[by,"Initial_to_peak PSA Curve"])
#     # psa_peak_to_recovery_curve = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Curve"])

#     psa_initial_crab = pd.DataFrame(columns=[by,"Initial PSA Crab"])
#     psa_final_crab = pd.DataFrame(columns=[by,"Final PSA Crab"])
#     psa_recovery_crab = pd.DataFrame(columns=[by,"Recovery PSA Crab"])
#     psa_peak_crab = pd.DataFrame(columns=[by,"Peak PSA Crab"])
#     # psa_peak_tap_crab = pd.DataFrame(columns=[by,"Peak Tap Number of PSA Crab"])
#     psa_avg_crab = pd.DataFrame(columns=[by,"Average PSA Crab"])
#     psa_sensitization_crab = pd.DataFrame(columns=[by,"Sensitization of PSA Crab"])
#     psa_habituation_crab = pd.DataFrame(columns=[by,"Habituation of PSA Crab"])
#     psa_spontaneous_recovery_crab = pd.DataFrame(columns=[by,"Spontaneous Recovery of PSA Crab"])
#     psa_memory_retention_crab = pd.DataFrame(columns=[by,"Memory Retention of PSA Crab"])
#     # psa_initial_to_peak_crab = pd.DataFrame(columns=[by,"Initial_to_peak PSA Crab"])
#     # psa_peak_to_recovery_crab = pd.DataFrame(columns=[by,"Peak_to_recovery PSA Crab"])

#     list_psa_Tstats = [
#         # psa_initial_speed, psa_final_speed,psa_recovery_speed, psa_peak_speed, psa_peak_tap_speed, psa_avg_speed,
#         psa_initial_speed, psa_final_speed,psa_recovery_speed, psa_peak_speed, psa_avg_speed,
#         psa_sensitization_speed, psa_habituation_speed, psa_spontaneous_recovery_speed, psa_memory_retention_speed,

#         # psa_initial_bias, psa_final_bias, psa_recovery_bias, psa_peak_bias, psa_peak_tap_bias, psa_avg_bias,
#         psa_initial_bias, psa_final_bias, psa_recovery_bias, psa_peak_bias, psa_avg_bias,
#         psa_sensitization_bias, psa_habituation_bias, psa_spontaneous_recovery_bias, psa_memory_retention_bias,

#         # psa_initial_ang_speed, psa_final_ang_speed, psa_recovery_ang_speed, psa_peak_ang_speed, psa_avg_ang_speed,
#         # psa_sensitization_ang_speed, psa_habituation_ang_speed, psa_spontaneous_recovery_ang_speed, psa_memory_retention_ang_speed,

#         psa_initial_aspect, psa_final_aspect, psa_recovery_aspect, psa_peak_aspect, psa_avg_aspect,
#         psa_sensitization_aspect, psa_habituation_aspect, psa_spontaneous_recovery_aspect, psa_memory_retention_aspect,

#         psa_initial_kink, psa_final_kink, psa_recovery_kink, psa_peak_kink, psa_avg_kink,
#         psa_sensitization_kink, psa_habituation_kink, psa_spontaneous_recovery_kink, psa_memory_retention_kink,

#         psa_initial_curve, psa_final_curve, psa_recovery_curve, psa_peak_curve, psa_avg_curve,
#         psa_sensitization_curve, psa_habituation_curve, psa_spontaneous_recovery_curve, psa_memory_retention_curve,

#         psa_initial_crab, psa_final_crab, psa_recovery_crab, psa_peak_crab, psa_avg_crab,
#         psa_sensitization_crab, psa_habituation_crab, psa_spontaneous_recovery_crab, psa_memory_retention_crab
#     ]

#     list_psa_metrics = [
#     "Initial PSA Speed",
#     "Final PSA Speed",
#     "Recovery PSA Speed",
#     "Peak PSA Speed",
#     # "Peak Tap Number of PSA Speed",
#     "Average PSA Speed",
#     "Sensitization of PSA Speed",
#     "Habituation of PSA Speed",
#     "Spontaneous Recovery of PSA Speed",
#     "Memory Retention of PSA Speed",

#     "Initial PSA Bias",
#     "Final PSA Bias",
#     "Recovery PSA Bias",
#     "Peak PSA Bias",
#     # "Peak Tap Number of PSA Bias",
#     "Average PSA Bias",
#     "Sensitization of PSA Bias",
#     "Habituation of PSA Bias",
#     "Spontaneous Recovery of PSA Bias",
#     "Memory Retention of PSA Bias",

#     # "Initial PSA Angular Speed",
#     # "Final PSA Angular Speed",
#     # "Recovery PSA Angular Speed",
#     # "Peak PSA Angular Speed",
#     # # "Peak Tap Number of PSA Angular Speed",
#     # "Average PSA Angular Speed",
#     # "Sensitization of PSA Angular Speed",
#     # "Habituation of PSA Angular Speed",
#     # "Spontaneous Recovery of PSA Angular Speed",
#     # "Memory Retention of PSA Angular Speed",

#     "Initial PSA Aspect Ratio",
#     "Final PSA Aspect Ratio",
#     "Recovery PSA Aspect Ratio",
#     "Peak PSA Aspect Ratio",
#     # "Peak Tap Number of PSA Aspect Ratio",
#     "Average PSA Aspect Ratio",
#     "Sensitization of PSA Aspect Ratio",
#     "Habituation of PSA Aspect Ratio",
#     "Spontaneous Recovery of PSA Aspect Ratio",
#     "Memory Retention of PSA Aspect Ratio",


#     "Initial PSA Kink",
#     "Final PSA Kink",
#     "Recovery PSA Kink",
#     "Peak PSA Kink",
#     # "Peak Tap Number of PSA Kink",
#     "Average PSA Kink",
#     "Sensitization of PSA Kink",
#     "Habituation of PSA Kink",
#     "Spontaneous Recovery of PSA Kink",
#     "Memory Retention of PSA Kink",

#     "Initial PSA Curve",
#     "Final PSA Curve",
#     "Recovery PSA Curve",
#     "Peak PSA Curve",
#     # "Peak Tap Number of PSA Curve",
#     "Average PSA Curve",
#     "Sensitization of PSA Curve",
#     "Habituation of PSA Curve",
#     "Spontaneous Recovery of PSA Curve",
#     "Memory Retention of PSA Curve",

#     "Initial PSA Crab",
#     "Final PSA Crab",
#     "Recovery PSA Crab",
#     "Peak PSA Crab",
#     # "Peak Tap Number of PSA Crab",
#     "Average PSA Crab",
#     "Sensitization of PSA Crab",
#     "Habituation of PSA Crab",
#     "Spontaneous Recovery of PSA Crab",
#     "Memory Retention of PSA Crab"
# ]
    
#     return list_psa_Tstats, list_psa_metrics

In [131]:
def TTest(Type, DF_ref, output, by=["Gene", "dataset"]):
    """
    Perform two sample t-test for each unique Gene/dataset column in the Df_ref
    input: 
        - a:column name of values 
        - DF_ref:reference dataframe
        - output: output df to store results in 
        - by: what to group by "Gene" or "dataset"
        
    """
    for a in DF_ref[by].unique():
        Tstat_a = ttest_ind(DF_ref[DF_ref.dataset == a][Type], DF_ref[DF_ref.Allele.isin(["XJ1","N2"])][Type],equal_var=False)[0]
        # print("This is Tstat_a:", Tstat_a)
        Tstat_a_pval = ttest_ind(DF_ref[DF_ref.dataset == a][Type], DF_ref[DF_ref.Allele.isin(["XJ1","N2"])][Type],equal_var=False)[1]
        # print("This is Tstat_a_pval:", Tstat_a_pval)
        Tstat_g = ttest_ind(DF_ref[DF_ref.Gene == a][Type], DF_ref[DF_ref.Gene == "N2"][Type],equal_var=False)[0]
        # print("This is Tstat_g:", Tstat_g)
        Tstat_g_pval = ttest_ind(DF_ref[DF_ref.Gene == a][Type], DF_ref[DF_ref.Gene == "N2"][Type],equal_var=False)[1]
        # print("This is Tstat_g_pval:", Tstat_g_pval)
        Tstat = Tstat_g if by=="Gene" else Tstat_a
        Tstat_pval = Tstat_g_pval if by=="Gene" else Tstat_a_pval
        row = [a, Tstat, Tstat_pval]
        # print(row)
        output.loc[len(output)] = row
    # print(output)

def do_TTest(by=["Gene", "dataset"], baseline=["true", "false", "psa"]):
    """
    Perform TTest function for each unique Gene/dataset column in baseline_output/tap_data
    
    input: 
        - by: what to group by "Gene" or "dataset"
        - baseline: whether or not to use baseline data

    returns: sorted T-statistics dataframe
    """

    if baseline=="true":
        list_Tstats, list_metrics = baseline_metrics(by)
        data = baseline_output
    elif baseline=="false":
        list_Tstats,list_metrics = tap_metrics(by)
        data = tap_data.dropna()
    else:
        pass
        # list_Tstats,list_metrics = psa_metrics(by)
        # data = psa_data
    for x in data[by].unique():
        if Screen=="Neuron_Genes_Screen":
            condition = x in (["N2"] if by == "Gene" else ["N2_XJ1", "N2_N2"])
        else:
            condition = (x =="N2")
        if condition:
            pass
        else:
            output_gene=data[data[by]==x]
            gene_data=data[data['Date'].isin(output_gene['Date'].unique())]
            if Screen=="Neuron_Genes_Screen":
                gene_data_final = gene_data[gene_data[by].isin(['N2', x])] if by=="Gene" else gene_data[gene_data[by].isin(['N2_N2','N2_XJ1', x])]
            else:
                gene_data_final = gene_data[gene_data[by].isin(['N2', x])]

            for a,b in zip(list_metrics, list_Tstats):
                TTest(a, gene_data_final, b, by) # calls t test function
    
    PD_Tstats=pd.DataFrame()
    for a in list_Tstats:
        b=a.groupby([by], as_index=False).mean()
        if b.columns.values[1] == list_Tstats[0].columns.values[1]:
            PD_Tstats=b
        else:
            PD_Tstats=PD_Tstats.join(b.iloc[:,1:3])
            
    PD_Tstats=PD_Tstats.set_index(by)
    
    return PD_Tstats

### T-stat on Baseline data:

### 3.3.1 Allele-level T-stat analysis of baseline data

In [118]:
warnings.filterwarnings('ignore')

PD_baseline_Tstats_allele = do_TTest("dataset", baseline="true") # get sorted T-statistics DataFrame 

# PD_baseline_Tstats_allele_sorted=PD_baseline_Tstats_allele.sort_index()

PD_baseline_Tstats_allele.head()

,Speed,Speed p-value,Bias,Bias p-value,Morphwidth,Morphwidth p-value,Midline,Midline p-value,Area,Area p-value,...,Aspect Ratio,Aspect Ratio p-value,Kink,Kink p-value,Curve,Curve p-value,Crab,Crab p-value,Pathlength,Pathlength p-value
dataset,,,,,,,,,,,,,,,,,,,,,
AMshABLATE_nsIs109,-170.402072,0.000000,-129.051227,0.000000e+00,8.436649,3.680577e-17,-72.062483,0.0,-19.016885,2.716644e-79,...,67.186598,0.0,60.225199,0.000000e+00,-59.206564,0.000000,-76.040905,0.000000e+00,-174.635472,0.000000e+00
N2,0.000000,1.000000,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.0,0.000000,1.000000e+00,...,0.000000,1.0,0.000000,1.000000e+00,0.000000,1.000000,0.000000,1.000000e+00,0.000000,1.000000e+00
ced-10_n3246,-178.516631,0.000000,-101.994376,0.000000e+00,-96.420955,0.000000e+00,-590.226320,0.0,-328.825337,0.000000e+00,...,324.132657,0.0,276.511600,0.000000e+00,81.799335,0.000000,7.820200,5.385267e-15,34.234078,6.399412e-254
ced-5_n2002,-124.360515,0.000000,-87.457709,0.000000e+00,-162.535954,0.000000e+00,-311.278255,0.0,-347.893201,0.000000e+00,...,-59.527752,0.0,-97.326696,0.000000e+00,-156.138037,0.000000,-58.958304,0.000000e+00,-33.193366,2.835850e-238
delm-1_ok1226,-3.381671,0.000721,-7.161008,8.127739e-13,-335.410406,0.000000e+00,-670.970972,0.0,-489.588565,0.000000e+00,...,58.931913,0.0,9.494694,2.325698e-21,-2.329122,0.019858,56.520463,0.000000e+00,106.468057,0.000000e+00

In [137]:
PD_baseline_Tstats_allele

,Speed,Speed p-value,Bias,Bias p-value,Morphwidth,Morphwidth p-value,Midline,Midline p-value,Area,Area p-value,...,Aspect Ratio,Aspect Ratio p-value,Kink,Kink p-value,Curve,Curve p-value,Crab,Crab p-value,Pathlength,Pathlength p-value
dataset,,,,,,,,,,,,,,,,,,,,,
AMshABLATE_nsIs109,-170.402072,0.000000e+00,-129.051227,0.000000e+00,8.436649,3.680577e-17,-72.062483,0.000000e+00,-19.016885,2.716644e-79,...,67.186598,0.000000e+00,60.225199,0.000000e+00,-59.206564,0.000000e+00,-76.040905,0.000000e+00,-174.635472,0.000000e+00
N2,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,...,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00
ced-10_n3246,-178.516631,0.000000e+00,-101.994376,0.000000e+00,-96.420955,0.000000e+00,-590.226320,0.000000e+00,-328.825337,0.000000e+00,...,324.132657,0.000000e+00,276.511600,0.000000e+00,81.799335,0.000000e+00,7.820200,5.385267e-15,34.234078,6.399412e-254
ced-5_n2002,-124.360515,0.000000e+00,-87.457709,0.000000e+00,-162.535954,0.000000e+00,-311.278255,0.000000e+00,-347.893201,0.000000e+00,...,-59.527752,0.000000e+00,-97.326696,0.000000e+00,-156.138037,0.000000e+00,-58.958304,0.000000e+00,-33.193366,2.835850e-238
delm-1_ok1226,-3.381671,7.210494e-04,-7.161008,8.127739e-13,-335.410406,0.000000e+00,-670.970972,0.000000e+00,-489.588565,0.000000e+00,...,58.931913,0.000000e+00,9.494694,2.325698e-21,-2.329122,1.985754e-02,56.520463,0.000000e+00,106.468057,0.000000e+00
delm-2_ok1822,54.519154,0.000000e+00,50.017138,0.000000e+00,-73.015252,0.000000e+00,-123.041801,0.000000e+00,-121.962871,0.000000e+00,...,53.839533,0.000000e+00,-13.937707,4.492784e-44,-16.127733,2.238279e-58,65.759874,0.000000e+00,-22.124802,6.570844e-108
dyf-7_m537,-216.337526,0.000000e+00,-182.226480,0.000000e+00,-88.831048,0.000000e+00,-188.090482,0.000000e+00,-169.869220,0.000000e+00,...,-76.211264,0.000000e+00,-43.034806,0.000000e+00,-236.389405,0.000000e+00,-83.684148,0.000000e+00,-253.081225,0.000000e+00
gcy-18_nj38,70.191415,0.000000e+00,65.211437,0.000000e+00,37.183877,2.443607e-298,77.027467,0.000000e+00,62.429596,0.000000e+00,...,-12.573728,3.389907e-36,-35.119748,2.126132e-266,26.010460,4.532825e-148,19.571989,5.858836e-85,-37.002285,4.094078e-295
ifa-4_ok1717,-67.376476,0.000000e+00,-58.089708,0.000000e+00,-69.318946,0.000000e+00,-102.016340,0.000000e+00,-100.065131,0.000000e+00,...,38.747350,0.000000e+00,19.820382,4.307909e-87,-37.434820,1.157547e-302,10.053450,9.446216e-24,54.089476,0.000000e+00
ifa-4_ok1734,118.639386,0.000000e+00,117.084474,0.000000e+00,-126.587862,0.000000e+00,-228.625082,0.000000e+00,-203.128452,0.000000e+00,...,52.719108,0.000000e+00,-40.863287,0.000000e+00,-170.327209,0.000000e+00,103.118092,0.000000e+00,126.263710,0.000000e+00
lgc-55_n4331,-12.611925,2.060046e-36,-20.026831,7.246633e-89,39.893291,0.000000e+00,104.838291,0.000000e+00,79.972314,0.000000e+00,...,-82.250891,0.000000e+00,-62.623016,0.000000e+00,-38.661861,0.000000e+00,-46.726050,0.000000e+00,-33.184373,7.273786e-239
lit-1_ne1991,385.971427,0.000000e+00,355.187793,0.000000e+00,-4.760162,1.939276e-06,132.441422,0.000000e+00,86.539524,0.000000e+00,...,231.322963,0.000000e+00,96.383112,0.000000e+00,333.398353,0.000000e+00,313.666609,0.000000e+00,208.007417,0.000000e+00
mgl-2_tm355,-197.746864,0.000000e+00,-170.470132,0.000000e+00,-145.966398,0.000000e+00,-176.264858,0.000000e+00,-185.363454,0.000000e+00,...,5.957484,2.580292e-09,125.625725,0.000000e+00,-50.455127,0.000000e+00,-28.936602,8.468077e-183,-133.728764,0.000000e+00
mgl-2xmgl-1_tm355xtm1811,161.533073,0.000000e+00,182.769679,0.000000e+00,12.610672,2.154403e-36,25.020237,9.266267e-137,20.368716,1.214063e-91,...,121.169930,0.000000e+00,86.095508,0.000000e+00,190.369109,0.000000e+00,148.483382,0.000000e+00,158.381371,0.000000e+00
mir-235_n4504,0.971905,3.311102e-01,33.326420,2.410903e-237,-24.954556,1.009283e-135,-3.967748,7.278521e-05,-5.666854,1.472604e-08,...,-33.117606,2.869227e-234,-40.453155,0.000000e+00,-12.619344,2.154974e-36,13.128553,3.075842e-39,126.820591,0.000000e+00
pde-1_ok2924,-58.280073,0.000000e+00,-16.956837,2.563206e-64,18.944860,9.457180e-80,-138.360000,0.000000e+00,-80.024272,0.000000e+00,...,77.220618,0.000000e+00,57.385422,0.000000e+00,-45.509901,0.000000e+00,2.492107,1.270180e-02,13.424117,5.570395e-41
ptp-3_ok2428,-89.562117,0.000000e+00,-63.232137,0.000000e+00,-151.198001,0.000000e+00,-383.572203,0.000000e+00,-326.556688,0.000000e+00,...,-48.519164,0.000000e+00,-27.736255,2.139561e-166,-178.552878,0.000000e+00,-38.077635,9.269855e-307,85.200076,0.000000e+00
syg-1_ok3640,11.157427,8.040045e-29,26.137066,1.840301e-148,-108.776567,0.000000e+00,-189.200018,0.000000e+00,-212.571328,0.000000e+00,...,129.038230,0.000000e+00,93.546049,0.000000e+00,77.649277,0.000000e+00,59.432052,0.000000e+00,53.630078,0.000000e+00
tax-2_ok3403,-140.628484,0.000000e+00,-139.949441,0.000000e+00,-60.957344,0.000000e+00,-262.017141,0.000000e+00,-217.373927,0.000000e+00,...,106.011178,0.000000e+00,82.356508,0.000000e+00,-91.351584,0.000000e+00,-26.812144,1.036814e-155,1.618866,1.054854e-01
tax-2_p671,-68.717706,0.000000e+00,-45.384023,0.000000e+00,-55.445583,0.000000e+00,-150.812080,0.000000e+00,-134.327328,0.000000e+00,...,112.394539,0.000000e+00,64.340246,0.000000e+00,46.671679,0.000000e+00,14.444678,4.095781e-47,10.619149,2.714294e-26
tax-4_ks11,-108.324242,0.000000e+00,-100.254203,0.000000e+00,-79.244376,0.000000e+00,-252.426474,0.000000e+00,-242.679230,0.000000e+00,...,149.556349,0.000000e+00,135.757228,0.000000e+00,-43.881726,0.000000e+00,-1.732569,8.318947e-02,-22.751570,1.868040e-113
tax-4_p678,-59.666116,0.000000e+00,-61.241884,0.000000e+00,-34.187538,3.086648e-249,-38.824880,0.000000e+00,-66.323940,0.000000e+00,...,81.094896,0.000000e+00,60.711819,0.000000e+00,46.884286,0.000000e+00,-0.693878,4.877661e-01,45.043841,0.000000e+00
unc-6_e78,-99.667355,0.000000e+00,-31.774268,1.000334e-216,-125.074063,0.000000e+00,-252.342066,0.000000e+00,-363.001043,0.000000e+00,...,325.401434,0.000000e+00,306.231040,0.000000e+00,69.422436,0.000000e+00,43.927558,0.000000e+00,-21.878068,2.081568e-104
ver-1_ok1738,-88.586513,0.000000e+00,-78.149194,0.000000e+00,-50.101620,0.000000e+00,-154.286488,0.000000e+00,-148.521819,0.000000e+00,...,-4.837504,1.324439e-06,-8.158756,3.577430e-16,-138.523549,0.000000e+00,-7.472392,8.241336e-14,-22.537744,9.926026e-111
ztf-16_ok1916,-114.931932,0.000000e+00,-47.377642,0.000000e+00,58.619865,0.000000e+00,-180.942466,0.000000e+00,-74.927942,0.000000e+00,...,97.116461,0.000000e+00,41.371956,0.000000e+00,-125.955456,0.000000e+00,15.063008,3.751543e-51,77.038386,0.000000e+00

### 3.3.2 Gene-level T-stat analysis of baseline data

In [119]:
warnings.filterwarnings('ignore')

PD_baseline_Tstats=do_TTest("Gene", baseline="true") # get sorted T-statistics DataFrame 

# PD_baseline_Tstats_sorted=PD_baseline_Tstats.sort_index()

PD_baseline_Tstats.head()

,Speed,Speed p-value,Bias,Bias p-value,Morphwidth,Morphwidth p-value,Midline,Midline p-value,Area,Area p-value,...,Aspect Ratio,Aspect Ratio p-value,Kink,Kink p-value,Curve,Curve p-value,Crab,Crab p-value,Pathlength,Pathlength p-value
Gene,,,,,,,,,,,,,,,,,,,,,
AMshABLATE,-170.402072,0.000000,-129.051227,0.000000e+00,8.436649,3.680577e-17,-72.062483,0.0,-19.016885,2.716644e-79,...,67.186598,0.0,60.225199,0.000000e+00,-59.206564,0.000000,-76.040905,0.000000e+00,-174.635472,0.000000e+00
N2,0.000000,1.000000,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.0,0.000000,1.000000e+00,...,0.000000,1.0,0.000000,1.000000e+00,0.000000,1.000000,0.000000,1.000000e+00,0.000000,1.000000e+00
ced-10,-178.516631,0.000000,-101.994376,0.000000e+00,-96.420955,0.000000e+00,-590.226320,0.0,-328.825337,0.000000e+00,...,324.132657,0.0,276.511600,0.000000e+00,81.799335,0.000000,7.820200,5.385267e-15,34.234078,6.399412e-254
ced-5,-124.360515,0.000000,-87.457709,0.000000e+00,-162.535954,0.000000e+00,-311.278255,0.0,-347.893201,0.000000e+00,...,-59.527752,0.0,-97.326696,0.000000e+00,-156.138037,0.000000,-58.958304,0.000000e+00,-33.193366,2.835850e-238
delm-1,-3.381671,0.000721,-7.161008,8.127739e-13,-335.410406,0.000000e+00,-670.970972,0.0,-489.588565,0.000000e+00,...,58.931913,0.0,9.494694,2.325698e-21,-2.329122,0.019858,56.520463,0.000000e+00,106.468057,0.000000e+00

In [136]:
PD_baseline_Tstats

,Speed,Speed p-value,Bias,Bias p-value,Morphwidth,Morphwidth p-value,Midline,Midline p-value,Area,Area p-value,...,Aspect Ratio,Aspect Ratio p-value,Kink,Kink p-value,Curve,Curve p-value,Crab,Crab p-value,Pathlength,Pathlength p-value
Gene,,,,,,,,,,,,,,,,,,,,,
AMshABLATE,-170.402072,0.000000e+00,-129.051227,0.000000e+00,8.436649,3.680577e-17,-72.062483,0.000000e+00,-19.016885,2.716644e-79,...,67.186598,0.000000e+00,60.225199,0.000000e+00,-59.206564,0.000000e+00,-76.040905,0.000000e+00,-174.635472,0.000000e+00
N2,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,...,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00
ced-10,-178.516631,0.000000e+00,-101.994376,0.000000e+00,-96.420955,0.000000e+00,-590.226320,0.000000e+00,-328.825337,0.000000e+00,...,324.132657,0.000000e+00,276.511600,0.000000e+00,81.799335,0.000000e+00,7.820200,5.385267e-15,34.234078,6.399412e-254
ced-5,-124.360515,0.000000e+00,-87.457709,0.000000e+00,-162.535954,0.000000e+00,-311.278255,0.000000e+00,-347.893201,0.000000e+00,...,-59.527752,0.000000e+00,-97.326696,0.000000e+00,-156.138037,0.000000e+00,-58.958304,0.000000e+00,-33.193366,2.835850e-238
delm-1,-3.381671,7.210494e-04,-7.161008,8.127739e-13,-335.410406,0.000000e+00,-670.970972,0.000000e+00,-489.588565,0.000000e+00,...,58.931913,0.000000e+00,9.494694,2.325698e-21,-2.329122,1.985754e-02,56.520463,0.000000e+00,106.468057,0.000000e+00
delm-2,54.519154,0.000000e+00,50.017138,0.000000e+00,-73.015252,0.000000e+00,-123.041801,0.000000e+00,-121.962871,0.000000e+00,...,53.839533,0.000000e+00,-13.937707,4.492784e-44,-16.127733,2.238279e-58,65.759874,0.000000e+00,-22.124802,6.570844e-108
dyf-7,-216.337526,0.000000e+00,-182.226480,0.000000e+00,-88.831048,0.000000e+00,-188.090482,0.000000e+00,-169.869220,0.000000e+00,...,-76.211264,0.000000e+00,-43.034806,0.000000e+00,-236.389405,0.000000e+00,-83.684148,0.000000e+00,-253.081225,0.000000e+00
gcy-18,70.191415,0.000000e+00,65.211437,0.000000e+00,37.183877,2.443607e-298,77.027467,0.000000e+00,62.429596,0.000000e+00,...,-12.573728,3.389907e-36,-35.119748,2.126132e-266,26.010460,4.532825e-148,19.571989,5.858836e-85,-37.002285,4.094078e-295
ifa-4,30.613335,3.214048e-204,36.142950,8.941936e-283,-103.745373,0.000000e+00,-165.594932,0.000000e+00,-153.010637,0.000000e+00,...,54.917363,0.000000e+00,-12.162426,5.558235e-34,-113.041844,0.000000e+00,57.847041,0.000000e+00,102.840537,0.000000e+00
lgc-55,-12.611925,2.060046e-36,-20.026831,7.246633e-89,39.893291,0.000000e+00,104.838291,0.000000e+00,79.972314,0.000000e+00,...,-82.250891,0.000000e+00,-62.623016,0.000000e+00,-38.661861,0.000000e+00,-46.726050,0.000000e+00,-33.184373,7.273786e-239
lit-1,385.971427,0.000000e+00,355.187793,0.000000e+00,-4.760162,1.939276e-06,132.441422,0.000000e+00,86.539524,0.000000e+00,...,231.322963,0.000000e+00,96.383112,0.000000e+00,333.398353,0.000000e+00,313.666609,0.000000e+00,208.007417,0.000000e+00
mgl-2,-197.746864,0.000000e+00,-170.470132,0.000000e+00,-145.966398,0.000000e+00,-176.264858,0.000000e+00,-185.363454,0.000000e+00,...,5.957484,2.580292e-09,125.625725,0.000000e+00,-50.455127,0.000000e+00,-28.936602,8.468077e-183,-133.728764,0.000000e+00
mgl-2xmgl-1,161.533073,0.000000e+00,182.769679,0.000000e+00,12.610672,2.154403e-36,25.020237,9.266267e-137,20.368716,1.214063e-91,...,121.169930,0.000000e+00,86.095508,0.000000e+00,190.369109,0.000000e+00,148.483382,0.000000e+00,158.381371,0.000000e+00
mir-235,0.971905,3.311102e-01,33.326420,2.410903e-237,-24.954556,1.009283e-135,-3.967748,7.278521e-05,-5.666854,1.472604e-08,...,-33.117606,2.869227e-234,-40.453155,0.000000e+00,-12.619344,2.154974e-36,13.128553,3.075842e-39,126.820591,0.000000e+00
pde-1,-58.280073,0.000000e+00,-16.956837,2.563206e-64,18.944860,9.457180e-80,-138.360000,0.000000e+00,-80.024272,0.000000e+00,...,77.220618,0.000000e+00,57.385422,0.000000e+00,-45.509901,0.000000e+00,2.492107,1.270180e-02,13.424117,5.570395e-41
ptp-3,-89.562117,0.000000e+00,-63.232137,0.000000e+00,-151.198001,0.000000e+00,-383.572203,0.000000e+00,-326.556688,0.000000e+00,...,-48.519164,0.000000e+00,-27.736255,2.139561e-166,-178.552878,0.000000e+00,-38.077635,9.269855e-307,85.200076,0.000000e+00
syg-1,11.157427,8.040045e-29,26.137066,1.840301e-148,-108.776567,0.000000e+00,-189.200018,0.000000e+00,-212.571328,0.000000e+00,...,129.038230,0.000000e+00,93.546049,0.000000e+00,77.649277,0.000000e+00,59.432052,0.000000e+00,53.630078,0.000000e+00
tax-2,-106.141950,0.000000e+00,-95.420027,0.000000e+00,-61.945022,0.000000e+00,-213.819212,0.000000e+00,-184.964449,0.000000e+00,...,129.037537,0.000000e+00,83.359286,0.000000e+00,-21.839077,7.995795e-105,-4.096988,4.202561e-05,6.974363,3.145449e-12
tax-4,-88.382922,0.000000e+00,-89.665292,0.000000e+00,-59.849587,0.000000e+00,-144.111190,0.000000e+00,-152.487706,0.000000e+00,...,139.680428,0.000000e+00,114.599543,0.000000e+00,-1.514498,1.299123e-01,-1.291708,1.964762e-01,8.652729,5.410392e-18
unc-6,-99.667355,0.000000e+00,-31.774268,1.000334e-216,-125.074063,0.000000e+00,-252.342066,0.000000e+00,-363.001043,0.000000e+00,...,325.401434,0.000000e+00,306.231040,0.000000e+00,69.422436,0.000000e+00,43.927558,0.000000e+00,-21.878068,2.081568e-104
ver-1,-88.586513,0.000000e+00,-78.149194,0.000000e+00,-50.101620,0.000000e+00,-154.286488,0.000000e+00,-148.521819,0.000000e+00,...,-4.837504,1.324439e-06,-8.158756,3.577430e-16,-138.523549,0.000000e+00,-7.472392,8.241336e-14,-22.537744,9.926026e-111
ztf-16,-114.931932,0.000000e+00,-47.377642,0.000000e+00,58.619865,0.000000e+00,-180.942466,0.000000e+00,-74.927942,0.000000e+00,...,97.116461,0.000000e+00,41.371956,0.000000e+00,-125.955456,0.000000e+00,15.063008,3.751543e-51,77.038386,0.000000e+00

### T-stat analysis for tap-response data:

### 3.3.3 Allele level T-stat analysis of tap response data

In [129]:
tap_data

,dataset,Gene,Allele,Date,Plate_id,plate,Screen,init_dura,init_prob,init_speed,...,mean_psa_aspect_ratio,mean_psa_kink,mean_psa_curve,mean_psa_crab,sensitization_psa_speed,sensitization_psa_bias,sensitization_psa_aspect_ratio,sensitization_psa_kink,sensitization_psa_curve,sensitization_psa_crab
0,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_023625_A0724,1.0,Glia_Genes_Screen,2.22,1.000000,0.253153,...,0.2915,48.5180,31.5382,0.0141,0.129852,0.722417,-0.000028,-0.000021,-0.000031,0.009069
1,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_032303_A0724,2.0,Glia_Genes_Screen,1.82,0.666667,0.224176,...,0.2956,49.5745,31.3311,0.0128,0.125366,0.649579,0.069915,17.899945,0.839068,0.010774
2,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101025_B0724,3.0,Glia_Genes_Screen,2.56,0.844444,0.178516,...,0.2997,48.6269,30.1888,0.0127,0.160250,0.685533,0.014733,6.523133,0.000033,0.014727
3,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_101818_C0724,4.0,Glia_Genes_Screen,2.95,0.760870,0.166441,...,0.3090,49.7521,31.4205,0.0138,0.131605,0.692568,-0.000026,0.000037,-0.000016,0.011984
4,AMshABLATE_nsIs109,AMshABLATE,nsIs109,20240724,20240724_110244_B0724,5.0,Glia_Genes_Screen,2.50,0.764706,0.168400,...,0.3032,49.0950,30.4203,0.0119,0.143737,0.703800,0.050033,0.190300,-0.000033,0.011670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_134421_A0313,8.0,Glia_Genes_Screen,2.30,0.838710,0.193913,...,0.3122,50.8310,33.1769,0.0139,0.122097,0.867067,0.035183,1.013333,0.953367,0.011245
314,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_200530_B0313,9.0,Glia_Genes_Screen,2.23,0.823529,0.170404,...,0.3049,44.8537,30.0586,0.0133,0.106692,0.830813,0.011692,3.659658,0.340977,0.007813
315,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_205323_C0313,10.0,Glia_Genes_Screen,2.69,0.804878,0.202602,...,0.3286,50.8685,31.2428,0.0120,0.094908,0.901261,0.087584,20.831174,2.764258,0.006061
316,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_215555_B0313,11.0,Glia_Genes_Screen,2.80,0.774194,0.159643,...,0.3270,52.1841,31.2238,0.0122,0.111468,0.901323,0.041627,4.384927,1.453600,0.009927
317,ztf-16_ok1916,ztf-16,ok1916,20250313,20250313_220015_C0313,12.0,Glia_Genes_Screen,1.99,0.731707,0.204020,...,0.3276,50.1867,31.2678,0.0134,0.098964,0.913666,0.000036,12.000121,-0.000026,0.006664

In [ ]:
warnings.filterwarnings('ignore')

PD_habituation_Tstats_allele = do_TTest("dataset", baseline="false") # get sorted T-statistics DataFrame 

# PD_habituation_Tstats_allele_sorted=PD_habituation_Tstats_allele.sort_index()

PD_habituation_Tstats_allele.head()

,Spontaneous Recovery of Response Duration,Spontaneous Recovery of Response Duration p-value,Spontaneous Recovery of Response Probability,Spontaneous Recovery of Response Probability p-value,Spontaneous Recovery of Response Speed,Spontaneous Recovery of Response Speed p-value,Memory Retention of Response Duration,Memory Retention of Response Duration p-value,Memory Retention of Response Probability,Memory Retention of Response Probability p-value,...,Average PSA Crab,Average PSA Crab p-value,Sensitization of PSA Crab,Sensitization of PSA Crab p-value,Habituation of PSA Crab,Habituation of PSA Crab p-value,Spontaneous Recovery of PSA Crab,Spontaneous Recovery of PSA Crab p-value,Memory Retention of PSA Crab,Memory Retention of PSA Crab p-value
dataset,,,,,,,,,,,,,,,,,,,,,
AMshABLATE_nsIs109,-1.961762,0.082259,1.918844,0.091826,-5.224931,0.000797,-5.484683,0.000578,-3.125683,1.221014e-02,...,-1.754747,1.154324e-01,3.086472,1.435338e-02,-0.265228,0.796970,-3.494769,0.009131,-2.495745,0.034306
N2,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000e+00,...,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
ced-10_n3246,-0.014609,0.988604,0.812373,0.433813,-0.172033,0.865583,-1.574401,0.131737,-3.281069,6.739752e-03,...,-0.677868,5.061759e-01,0.539237,5.998592e-01,-5.323231,0.000032,3.279944,0.004207,-0.902427,0.378349
ced-5_n2002,0.908764,0.402040,-2.606610,0.043382,-1.672565,0.127472,-1.643956,0.151332,-11.953176,2.056554e-07,...,-12.055992,9.487711e-09,-8.858175,3.695434e-07,-3.838380,0.001496,1.635382,0.142643,0.430096,0.672863
delm-1_ok1226,1.479204,0.174310,0.679554,0.512420,-0.081651,0.936168,0.352711,0.731880,0.613993,5.534931e-01,...,1.874706,7.703112e-02,-2.221744,4.595253e-02,-2.315809,0.041064,1.224244,0.244884,-1.595466,0.127292

In [133]:
PD_habituation_Tstats_allele

,Spontaneous Recovery of Response Duration,Spontaneous Recovery of Response Duration p-value,Spontaneous Recovery of Response Probability,Spontaneous Recovery of Response Probability p-value,Spontaneous Recovery of Response Speed,Spontaneous Recovery of Response Speed p-value,Memory Retention of Response Duration,Memory Retention of Response Duration p-value,Memory Retention of Response Probability,Memory Retention of Response Probability p-value,...,Average PSA Crab,Average PSA Crab p-value,Sensitization of PSA Crab,Sensitization of PSA Crab p-value,Habituation of PSA Crab,Habituation of PSA Crab p-value,Spontaneous Recovery of PSA Crab,Spontaneous Recovery of PSA Crab p-value,Memory Retention of PSA Crab,Memory Retention of PSA Crab p-value
dataset,,,,,,,,,,,,,,,,,,,,,
AMshABLATE_nsIs109,-1.961762,0.082259,1.918844,0.091826,-5.224931,0.000797,-5.484683,5.779923e-04,-3.125683,1.221014e-02,...,-1.754747,1.154324e-01,3.086472,1.435338e-02,-0.265228,7.969701e-01,-3.494769,0.009131,-2.495745,0.034306
N2,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000e+00,0.000000,1.000000e+00,...,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000,0.000000,1.000000
ced-10_n3246,-0.014609,0.988604,0.812373,0.433813,-0.172033,0.865583,-1.574401,1.317369e-01,-3.281069,6.739752e-03,...,-0.677868,5.061759e-01,0.539237,5.998592e-01,-5.323231,3.174942e-05,3.279944,0.004207,-0.902427,0.378349
ced-5_n2002,0.908764,0.402040,-2.606610,0.043382,-1.672565,0.127472,-1.643956,1.513315e-01,-11.953176,2.056554e-07,...,-12.055992,9.487711e-09,-8.858175,3.695434e-07,-3.838380,1.495845e-03,1.635382,0.142643,0.430096,0.672863
delm-1_ok1226,1.479204,0.174310,0.679554,0.512420,-0.081651,0.936168,0.352711,7.318801e-01,0.613993,5.534931e-01,...,1.874706,7.703112e-02,-2.221744,4.595253e-02,-2.315809,4.106408e-02,1.224244,0.244884,-1.595466,0.127292
delm-2_ok1822,1.168490,0.256323,-1.507889,0.149642,0.219849,0.828488,0.767811,4.525734e-01,-0.997519,3.337145e-01,...,3.497978,2.142703e-03,0.396955,6.958445e-01,-1.562881,1.336729e-01,1.272229,0.218473,-0.425204,0.675028
dyf-7_m537,2.178971,0.041184,0.268528,0.791709,1.597503,0.131084,0.902628,3.783623e-01,-1.399154,1.763781e-01,...,2.258355,3.717592e-02,1.655712,1.130523e-01,0.700746,4.911562e-01,1.758870,0.093525,3.686334,0.001462
gcy-18_nj38,-2.514678,0.021236,0.255981,0.800961,1.101173,0.285407,-1.550198,1.376713e-01,2.322069,3.220542e-02,...,3.623565,1.903431e-03,2.577966,1.843473e-02,-1.750453,9.698498e-02,1.583433,0.130643,0.269627,0.791350
ifa-4_ok1717,0.297707,0.769061,1.285322,0.212048,0.284452,0.778920,0.467972,6.448952e-01,-0.793870,4.358561e-01,...,-0.469713,6.432704e-01,-0.188949,8.520281e-01,-0.080907,9.362501e-01,0.234336,0.816943,0.090318,0.928887
ifa-4_ok1734,1.751350,0.095229,1.556526,0.142300,0.280444,0.783267,1.255848,2.238115e-01,0.467559,6.469716e-01,...,3.256626,4.006828e-03,-1.639181,1.173208e-01,-5.468538,5.548356e-05,4.335754,0.000353,-0.647482,0.524862
lgc-55_n4331,0.025841,0.979652,-1.702027,0.103659,3.343141,0.003249,0.457773,6.518393e-01,0.007562,9.940386e-01,...,2.823082,1.253598e-02,2.242577,3.588417e-02,-0.041104,9.676027e-01,1.549235,0.136370,1.954438,0.067370
lit-1_ne1991,0.756611,0.464698,-0.036504,0.971218,0.701829,0.491378,1.323625,2.031179e-01,0.280099,7.821799e-01,...,11.725501,7.206037e-09,0.161034,8.741659e-01,0.032560,9.745421e-01,0.156354,0.877498,-1.446571,0.165863
mgl-2_tm355,0.189619,0.851573,1.124087,0.273737,-0.869523,0.395114,-1.530249,1.415135e-01,-1.926166,6.787035e-02,...,-5.614240,2.336685e-05,-1.321662,2.009433e-01,0.106848,9.159863e-01,-0.070683,0.944415,0.458876,0.651149
mgl-2xmgl-1_tm355xtm1811,-1.385470,0.180726,-0.221381,0.827072,0.344127,0.734730,-2.985446,6.930921e-03,0.291553,7.752104e-01,...,1.159280,2.590929e-01,-2.317411,3.295336e-02,-2.262748,3.663898e-02,1.007260,0.324871,-0.605020,0.551670
mir-235_n4504,-0.283562,0.783158,-0.626088,0.543001,-0.595200,0.565195,-1.584811,1.423344e-01,-2.524254,2.886981e-02,...,-4.664531,6.387187e-04,-1.758237,1.118992e-01,-1.733613,1.134029e-01,0.799486,0.440519,-0.877284,0.399972
pde-1_ok2924,0.878910,0.395098,-0.703462,0.489474,1.193585,0.245363,0.758726,4.561676e-01,-2.097011,4.774885e-02,...,-3.957665,1.045159e-03,-0.834099,4.188742e-01,0.563870,5.785997e-01,-1.358071,0.189611,-0.896694,0.380197
ptp-3_ok2428,0.625378,0.557297,0.001873,0.998547,-1.385296,0.199330,0.316050,7.613109e-01,-2.606218,3.624134e-02,...,-4.797794,1.230763e-03,1.706629,1.225375e-01,-3.100054,2.250971e-02,0.733835,0.486698,-2.499762,0.047441
syg-1_ok3640,1.355793,0.214380,1.277815,0.251688,0.522730,0.615055,0.103197,9.199310e-01,0.801631,4.426208e-01,...,-0.159651,8.764159e-01,-0.049869,9.613088e-01,-1.706625,1.187529e-01,1.544473,0.160393,0.182573,0.859031
tax-2_ok3403,0.172536,0.866425,2.173241,0.048272,-0.662958,0.517953,1.096329,3.017907e-01,-2.709533,1.653677e-02,...,-4.754095,2.156123e-04,-1.980110,6.880309e-02,-0.747253,4.682349e-01,0.560906,0.582642,-0.111854,0.912332
tax-2_p671,-4.161598,0.000655,-1.689540,0.110487,0.141178,0.889273,-9.680781,2.466470e-07,-5.122427,1.347120e-04,...,-1.882186,7.688850e-02,-0.898425,3.822308e-01,-7.232828,2.406994e-06,1.377098,0.189124,-2.784428,0.020891
tax-4_ks11,-0.846161,0.409566,0.381441,0.707109,-2.288096,0.038201,2.106638,5.514346e-02,-6.058161,2.050495e-05,...,3.794273,1.439505e-03,0.576994,5.707725e-01,-2.907381,1.041855e-02,-0.237877,0.816110,-2.337248,0.032004
tax-4_p678,-1.125797,0.279555,-3.646618,0.001908,-0.681116,0.504552,-5.060376,1.065526e-04,-3.624653,2.042815e-03,...,2.715421,1.573311e-02,2.402606,2.728096e-02,-8.049632,6.387442e-07,2.161011,0.044537,-2.097395,0.055808
unc-6_e78,1.842966,0.107084,0.476416,0.650273,1.235219,0.253077,-2.611110,4.177668e-02,-2.329014,4.352190e-02,...,-5.446437,4.336645e-04,-1.725754,1.164798e-01,-5.067578,1.981913e-03,2.316774,0.045659,-1.137096,0.298789
ver-1_ok1738,0.995822,0.347070,1.324434,0.215007,-0.041594,0.967694,0.954257,3.625774e-01,-0.099708,9.225953e-01,...,-4.984253,1.587515e-03,-1.484085,1.767498e-01,-2.102143,6.463753e-02,1.028971,0.328417,-0.240117,0.817043
ztf-16_ok1916,0.643681,0.526774,0.524134,0.605725,1.803719,0.085059,-2.333885,2.930521e-02,-0.241858,8.118728e-01,...,-2.815298,1.123406e-02,-1.305680,2.060137e-01,-3.714073,2.035423e-03,1.286190,0.211771,-3.882831,0.001089

### 3.3.4 Gene-level T-stat analysis of Tap response data

In [134]:
warnings.filterwarnings('ignore')

PD_habituation_Tstats = do_TTest("Gene", baseline="false") # get sorted T-statistics DataFrame 

PD_habituation_Tstats_sorted=PD_habituation_Tstats.sort_index()

PD_habituation_Tstats.head()

,Spontaneous Recovery of Response Duration,Spontaneous Recovery of Response Duration p-value,Spontaneous Recovery of Response Probability,Spontaneous Recovery of Response Probability p-value,Spontaneous Recovery of Response Speed,Spontaneous Recovery of Response Speed p-value,Memory Retention of Response Duration,Memory Retention of Response Duration p-value,Memory Retention of Response Probability,Memory Retention of Response Probability p-value,...,Average PSA Crab,Average PSA Crab p-value,Sensitization of PSA Crab,Sensitization of PSA Crab p-value,Habituation of PSA Crab,Habituation of PSA Crab p-value,Spontaneous Recovery of PSA Crab,Spontaneous Recovery of PSA Crab p-value,Memory Retention of PSA Crab,Memory Retention of PSA Crab p-value
Gene,,,,,,,,,,,,,,,,,,,,,
AMshABLATE,-1.961762,0.082259,1.918844,0.091826,-5.224931,0.000797,-5.484683,0.000578,-3.125683,1.221014e-02,...,-1.754747,1.154324e-01,3.086472,1.435338e-02,-0.265228,0.796970,-3.494769,0.009131,-2.495745,0.034306
N2,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000e+00,...,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
ced-10,-0.014609,0.988604,0.812373,0.433813,-0.172033,0.865583,-1.574401,0.131737,-3.281069,6.739752e-03,...,-0.677868,5.061759e-01,0.539237,5.998592e-01,-5.323231,0.000032,3.279944,0.004207,-0.902427,0.378349
ced-5,0.908764,0.402040,-2.606610,0.043382,-1.672565,0.127472,-1.643956,0.151332,-11.953176,2.056554e-07,...,-12.055992,9.487711e-09,-8.858175,3.695434e-07,-3.838380,0.001496,1.635382,0.142643,0.430096,0.672863
delm-1,1.479204,0.174310,0.679554,0.512420,-0.081651,0.936168,0.352711,0.731880,0.613993,5.534931e-01,...,1.874706,7.703112e-02,-2.221744,4.595253e-02,-2.315809,0.041064,1.224244,0.244884,-1.595466,0.127292

In [135]:
PD_habituation_Tstats

,Spontaneous Recovery of Response Duration,Spontaneous Recovery of Response Duration p-value,Spontaneous Recovery of Response Probability,Spontaneous Recovery of Response Probability p-value,Spontaneous Recovery of Response Speed,Spontaneous Recovery of Response Speed p-value,Memory Retention of Response Duration,Memory Retention of Response Duration p-value,Memory Retention of Response Probability,Memory Retention of Response Probability p-value,...,Average PSA Crab,Average PSA Crab p-value,Sensitization of PSA Crab,Sensitization of PSA Crab p-value,Habituation of PSA Crab,Habituation of PSA Crab p-value,Spontaneous Recovery of PSA Crab,Spontaneous Recovery of PSA Crab p-value,Memory Retention of PSA Crab,Memory Retention of PSA Crab p-value
Gene,,,,,,,,,,,,,,,,,,,,,
AMshABLATE,-1.961762,0.082259,1.918844,0.091826,-5.224931,0.000797,-5.484683,0.000578,-3.125683,1.221014e-02,...,-1.754747,1.154324e-01,3.086472,1.435338e-02,-0.265228,0.796970,-3.494769,0.009131,-2.495745,0.034306
N2,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000e+00,...,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
ced-10,-0.014609,0.988604,0.812373,0.433813,-0.172033,0.865583,-1.574401,0.131737,-3.281069,6.739752e-03,...,-0.677868,5.061759e-01,0.539237,5.998592e-01,-5.323231,0.000032,3.279944,0.004207,-0.902427,0.378349
ced-5,0.908764,0.402040,-2.606610,0.043382,-1.672565,0.127472,-1.643956,0.151332,-11.953176,2.056554e-07,...,-12.055992,9.487711e-09,-8.858175,3.695434e-07,-3.838380,0.001496,1.635382,0.142643,0.430096,0.672863
delm-1,1.479204,0.174310,0.679554,0.512420,-0.081651,0.936168,0.352711,0.731880,0.613993,5.534931e-01,...,1.874706,7.703112e-02,-2.221744,4.595253e-02,-2.315809,0.041064,1.224244,0.244884,-1.595466,0.127292
delm-2,1.168490,0.256323,-1.507889,0.149642,0.219849,0.828488,0.767811,0.452573,-0.997519,3.337145e-01,...,3.497978,2.142703e-03,0.396955,6.958445e-01,-1.562881,0.133673,1.272229,0.218473,-0.425204,0.675028
dyf-7,2.178971,0.041184,0.268528,0.791709,1.597503,0.131084,0.902628,0.378362,-1.399154,1.763781e-01,...,2.258355,3.717592e-02,1.655712,1.130523e-01,0.700746,0.491156,1.758870,0.093525,3.686334,0.001462
gcy-18,-2.514678,0.021236,0.255981,0.800961,1.101173,0.285407,-1.550198,0.137671,2.322069,3.220542e-02,...,3.623565,1.903431e-03,2.577966,1.843473e-02,-1.750453,0.096985,1.583433,0.130643,0.269627,0.791350
ifa-4,1.091492,0.289851,1.532786,0.143041,0.319083,0.752712,0.911475,0.370915,-0.320919,7.516170e-01,...,1.187423,2.458816e-01,-0.881268,3.867590e-01,-2.242088,0.033651,2.052819,0.050284,-0.248189,0.806251
lgc-55,0.025841,0.979652,-1.702027,0.103659,3.343141,0.003249,0.457773,0.651839,0.007562,9.940386e-01,...,2.823082,1.253598e-02,2.242577,3.588417e-02,-0.041104,0.967603,1.549235,0.136370,1.954438,0.067370
lit-1,0.756611,0.464698,-0.036504,0.971218,0.701829,0.491378,1.323625,0.203118,0.280099,7.821799e-01,...,11.725501,7.206037e-09,0.161034,8.741659e-01,0.032560,0.974542,0.156354,0.877498,-1.446571,0.165863
mgl-2,0.189619,0.851573,1.124087,0.273737,-0.869523,0.395114,-1.530249,0.141513,-1.926166,6.787035e-02,...,-5.614240,2.336685e-05,-1.321662,2.009433e-01,0.106848,0.915986,-0.070683,0.944415,0.458876,0.651149
mgl-2xmgl-1,-1.385470,0.180726,-0.221381,0.827072,0.344127,0.734730,-2.985446,0.006931,0.291553,7.752104e-01,...,1.159280,2.590929e-01,-2.317411,3.295336e-02,-2.262748,0.036639,1.007260,0.324871,-0.605020,0.551670
mir-235,-0.283562,0.783158,-0.626088,0.543001,-0.595200,0.565195,-1.584811,0.142334,-2.524254,2.886981e-02,...,-4.664531,6.387187e-04,-1.758237,1.118992e-01,-1.733613,0.113403,0.799486,0.440519,-0.877284,0.399972
pde-1,0.878910,0.395098,-0.703462,0.489474,1.193585,0.245363,0.758726,0.456168,-2.097011,4.774885e-02,...,-3.957665,1.045159e-03,-0.834099,4.188742e-01,0.563870,0.578600,-1.358071,0.189611,-0.896694,0.380197
ptp-3,0.625378,0.557297,0.001873,0.998547,-1.385296,0.199330,0.316050,0.761311,-2.606218,3.624134e-02,...,-4.797794,1.230763e-03,1.706629,1.225375e-01,-3.100054,0.022510,0.733835,0.486698,-2.499762,0.047441
syg-1,1.355793,0.214380,1.277815,0.251688,0.522730,0.615055,0.103197,0.919931,0.801631,4.426208e-01,...,-0.159651,8.764159e-01,-0.049869,9.613088e-01,-1.706625,0.118753,1.544473,0.160393,0.182573,0.859031
tax-2,-1.681233,0.104008,0.380781,0.706746,-0.153835,0.879279,-1.591856,0.123870,-4.297636,7.964170e-04,...,-3.380530,2.431262e-03,-1.727246,9.980079e-02,-3.749660,0.000917,1.119739,0.282732,-1.519502,0.153355
tax-4,-1.299009,0.204080,-1.526688,0.140839,-1.593117,0.130769,-0.265219,0.792815,-5.289077,1.007297e-04,...,3.838974,7.803783e-04,1.679133,1.095563e-01,-5.391567,0.000011,1.126301,0.277676,-2.447161,0.030287
unc-6,1.842966,0.107084,0.476416,0.650273,1.235219,0.253077,-2.611110,0.041777,-2.329014,4.352190e-02,...,-5.446437,4.336645e-04,-1.725754,1.164798e-01,-5.067578,0.001982,2.316774,0.045659,-1.137096,0.298789
ver-1,0.995822,0.347070,1.324434,0.215007,-0.041594,0.967694,0.954257,0.362577,-0.099708,9.225953e-01,...,-4.984253,1.587515e-03,-1.484085,1.767498e-01,-2.102143,0.064638,1.028971,0.328417,-0.240117,0.817043
ztf-16,0.643681,0.526774,0.524134,0.605725,1.803719,0.085059,-2.333885,0.029305,-0.241858,8.118728e-01,...,-2.815298,1.123406e-02,-1.305680,2.060137e-01,-3.714073,0.002035,1.286190,0.211771,-3.882831,0.001089

### T-stat analysis for psa data:

### 3.3.5 Allele level T-stat analysis of PSA data * defunct *

In [ ]:
# warnings.filterwarnings('ignore')

# psa_tstats_allele = do_TTest("dataset", baseline="psa") # get sorted T-statistics DataFrame 

# psa_tstats_allele.head()

,Initial PSA Speed,Final PSA Speed,Recovery PSA Speed,Peak PSA Speed,Peak Tap Number of PSA Speed,Average PSA Speed,Sensitization of PSA Speed,Habituation of PSA Speed,Spontaneous Recovery of PSA Speed,Memory Retention of PSA Speed,...,Initial PSA Crab,Final PSA Crab,Recovery PSA Crab,Peak PSA Crab,Peak Tap Number of PSA Crab,Average PSA Crab,Sensitization of PSA Crab,Habituation of PSA Crab,Spontaneous Recovery of PSA Crab,Memory Retention of PSA Crab
dataset,,,,,,,,,,,,,,,,,,,,,
AMshABLATE_nsIs109,-2.879720,NaN,NaN,-2.413182,-1.487156,-8.056602,0.794525,NaN,NaN,NaN,...,-1.626474,NaN,NaN,1.866463,2.236068,-1.688506,3.070526,NaN,NaN,NaN
N2,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
ced-10_n3246,-8.285814,NaN,NaN,-4.366429,4.046460,-15.382731,-2.379847,NaN,NaN,NaN,...,-5.665189,NaN,NaN,-0.997846,3.725065,-0.423095,1.107303,NaN,NaN,NaN
ced-5_n2002,-8.461492,NaN,NaN,-4.288245,5.181633,-17.399081,-2.319622,NaN,NaN,NaN,...,-5.649231,NaN,NaN,-2.451194,2.905970,-6.280971,-0.709694,NaN,NaN,NaN
delm-1_ok1226,-1.618097,NaN,NaN,-8.571276,1.193799,-10.314660,-6.550509,NaN,NaN,NaN,...,0.740383,NaN,NaN,-0.416530,0.925338,2.197676,-2.258804,NaN,NaN,NaN

### 3.3.6 Gene-level T-stat analysis of PSA data

In [ ]:
# warnings.filterwarnings('ignore')

# psa_tstats = do_TTest("Gene", baseline="psa") # get sorted T-statistics DataFrame 

# psa_tstats.head()

,Initial PSA Speed,Final PSA Speed,Recovery PSA Speed,Peak PSA Speed,Peak Tap Number of PSA Speed,Average PSA Speed,Sensitization of PSA Speed,Habituation of PSA Speed,Spontaneous Recovery of PSA Speed,Memory Retention of PSA Speed,...,Initial PSA Crab,Final PSA Crab,Recovery PSA Crab,Peak PSA Crab,Peak Tap Number of PSA Crab,Average PSA Crab,Sensitization of PSA Crab,Habituation of PSA Crab,Spontaneous Recovery of PSA Crab,Memory Retention of PSA Crab
Gene,,,,,,,,,,,,,,,,,,,,,
AMshABLATE,-2.879720,NaN,NaN,-2.413182,-1.487156,-8.056602,0.794525,NaN,NaN,NaN,...,-1.626474,NaN,NaN,1.866463,2.236068,-1.688506,3.070526,NaN,NaN,NaN
N2,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
ced-10,-8.285814,NaN,NaN,-4.366429,4.046460,-15.382731,-2.379847,NaN,NaN,NaN,...,-5.665189,NaN,NaN,-0.997846,3.725065,-0.423095,1.107303,NaN,NaN,NaN
ced-5,-8.461492,NaN,NaN,-4.288245,5.181633,-17.399081,-2.319622,NaN,NaN,NaN,...,-5.649231,NaN,NaN,-2.451194,2.905970,-6.280971,-0.709694,NaN,NaN,NaN
delm-1,-1.618097,NaN,NaN,-8.571276,1.193799,-10.314660,-6.550509,NaN,NaN,NaN,...,0.740383,NaN,NaN,-0.416530,0.925338,2.197676,-2.258804,NaN,NaN,NaN

# 4. Merging t-stat data into one dataset

In [122]:
def pop_cols(combined):
    """
    Reorders columns in the combined dataframe. 
    (pops specific columns["Area", "Midline", "Morphwidth", "Angular Speed"] and
    reinserts at different positions)

    input:
        combined: dataframe with columns to be reordered

    returns: 
        NA    
        
    """
    first_col=combined.pop("Area")
    combined.insert(0,"Area",first_col)

    first_col=combined.pop("Midline")
    combined.insert(0,"Midline",first_col)

    first_col=combined.pop("Morphwidth")
    combined.insert(0,"Morphwidth",first_col)

    first_col=combined.pop("Angular Speed")
    combined.insert(5,"Angular Speed",first_col)

def pop_last(combined):
    """
    Reorders the last three columns of the combined dataframe.
    input:
        combined: dataframe with columns to be reordered

    """
    last_col=combined.pop("Spontaneous Recovery of Response Duration")
    combined.insert(25,"Spontaneous Recovery of Response Duration",last_col)

    last_col=combined.pop("Spontaneous Recovery of Response Probability")
    combined.insert(25,"Spontaneous Recovery of Response Probability",last_col)

    last_col=combined.pop("Spontaneous Recovery of Response Speed")
    combined.insert(25,"Spontaneous Recovery of Response Speed",last_col)

    last_col=combined.pop("Memory Retention of Response Duration")
    combined.insert(25,"Memory Retention of Response Duration",last_col)

    last_col=combined.pop("Memory Retention of Response Probability")
    combined.insert(25,"Memory Retention of Response Probability",last_col)

    last_col=combined.pop("Memory Retention of Response Speed")
    combined.insert(25,"Memory Retention of Response Speed",last_col)

def rename_columns(df):
    '''
    Renames columns in the input dataframe
    input:
        combined: dataframe with columns to be renamed   
    returns:
        input dataframe with renamed columns 
    '''
    renames = {
        "Habituation of Duration": "Habituation of Response Duration",
        "Habituation of Probability": "Habituation of Response Probability",
        "Habituation of Speed": "Habituation of Response Speed",
        "Initial Duration": "Initial Response Duration",
        "Initial Probability": "Initial Response Probability",
        "Initial Speed": "Initial Response Speed",
        "Final Duration": "Final Response Duration",
        "Final Probability": "Final Response Probability",
        "Final Speed": "Final Response Speed",
        "Recovery Duration": "Spontaneous Recovery of Response Duration",
        "Recovery Probability": "Spontaneous Recovery of Response Probability",
        "Recovery Speed": "Spontaneous Recovery of Response Speed",
        "Memory Retention Duration": "Memory Retention of Response Duration",
        "Memory Retention Probability": "Memory Retention of Response Probability",
        "Memory Retention Speed": "Memory Retention of Response Speed"
    }
    return df.rename(columns=renames)

def merge_Tstats(baseline, habituation, by=["Gene", "dataset"], Screen=Screen, psa=False):
    """
    merge baseline and tap response dataframes based on the Gene/dataset
    normalize the merged dataframe and then return it with melted version

    input:
        - baseline: baseline dataframe to merge
        - habituation: habituation dataframe to merge
        - by: what to group by "Gene" or "dataset"
    """

    #merge baseline and habituation data
    combined_Tstats = pd.merge(baseline, habituation, on=by, how='left')
    combined_Tstats = combined_Tstats.sort_index() # sort by index

    # ------------ NORMALISATION STEPS MOVED TO DASHBOARD -------------------
    # # normalise combined dataframe by subtracting mean and div by sd
    # combined_Tstats_normalized = (combined_Tstats-combined_Tstats.mean())/combined_Tstats.std()

    # if by=="dataset" and Screen=="Neuron_Genes_Screen":
    #     combined_Tstats_normalized_2 = combined_Tstats-combined_Tstats[combined_Tstats.index=="N2_XJ1"].squeeze()
    # else :
    #     combined_Tstats_normalized_2 = combined_Tstats-combined_Tstats[combined_Tstats.index=="N2"].squeeze()  

    pop_cols(combined_Tstats) # reorder columns

    # Skip this step if data = psa
    if not psa:
        #rename columns of combined and normalized df
        combined_Tstats = rename_columns(combined_Tstats)
        # combined_Tstats_normalized_2=rename_columns(combined_Tstats_normalized_2)
        pop_cols(combined_Tstats) # reorder columns
        pop_last(combined_Tstats) # reorder columns

    # -------------- PIVOTING STEPS MOVED TO DASHBOARD ---------------------
    # # Melt the combined dataframe
    # combined_Tstats_melted=combined_Tstats.reset_index()
    # combined_Tstats_melted=pd.melt(combined_Tstats_melted, id_vars=[by],
    #                             var_name='Metric',
    #                             value_name='T_score')
    
    # # Sort the melted dataframe by T_score
    # combined_Tstats_melted_sorted=combined_Tstats_melted.sort_values(by=['T_score'])

    # # Melt the normalized dataframe
    # combined_Tstats_normalized_melted=combined_Tstats.reset_index()
    # combined_Tstats_normalized_melted=pd.melt(combined_Tstats_normalized_melted, id_vars=[by],
    #                                                var_name='Metric',
    #                                                value_name='T_score')

    # add Screen column to df and its melted version
    combined_Tstats['Screen']=Screen
    # combined_Tstats_normalized_melted['Screen']=Screen

    return combined_Tstats#, combined_Tstats_normalized_melted

def reorder_screencolumn(df):
    """
    Reorders the 'Screen' column to be the second column in the dataframe.

    input:
        df: DataFrame with a 'Screen' column

    returns:
        DataFrame with 'Screen' as the second column
    """
    cols = df.columns.tolist()
    if 'Screen' in cols:
        cols.insert(1, cols.pop(cols.index('Screen')))
        df = df[cols]
    return df

## 4.1 Gene-level

- Pass Tap and baseline through merge_Tstats() as df1
- Pass PSA and baseline through merge_Tstats()as df2
- pd.merge df1 and df2 using all columns of baseline

In [123]:
# Baseline + Tap
combined_Tstats = merge_Tstats(PD_baseline_Tstats, PD_habituation_Tstats, "Gene")

In [124]:
# Baseline + PSA 
combined_Tstats_psa = merge_Tstats(
    PD_baseline_Tstats, psa_tstats, by="Gene", psa=True
)

In [125]:
# Baseline + Tap + PSA
final_tstat = pd.merge(combined_Tstats.reset_index(), combined_Tstats_psa.reset_index(), on = PD_baseline_Tstats.columns.to_list().append(['Gene','Screen']), how = 'inner')
# final_tstat = reorder_screencolumn(final_tstat)
final_tstat.head()

,Gene,Morphwidth,Midline,Area,Speed,Bias,Angular Speed,Aspect Ratio,Kink,Curve,...,Initial PSA Crab,Final PSA Crab,Recovery PSA Crab,Peak PSA Crab,Peak Tap Number of PSA Crab,Average PSA Crab,Sensitization of PSA Crab,Habituation of PSA Crab,Spontaneous Recovery of PSA Crab,Memory Retention of PSA Crab
0,AMshABLATE,8.436649,-72.062483,-19.016885,-170.402072,-129.051227,-72.427009,67.186598,60.225199,-59.206564,...,-1.626474,NaN,NaN,1.866463,2.236068,-1.688506,3.070526,NaN,NaN,NaN
1,N2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
2,ced-10,-96.420955,-590.226320,-328.825337,-178.516631,-101.994376,86.467808,324.132657,276.511600,81.799335,...,-5.665189,NaN,NaN,-0.997846,3.725065,-0.423095,1.107303,NaN,NaN,NaN
3,ced-5,-162.535954,-311.278255,-347.893201,-124.360515,-87.457709,6.824703,-59.527752,-97.326696,-156.138037,...,-5.649231,NaN,NaN,-2.451194,2.905970,-6.280971,-0.709694,NaN,NaN,NaN
4,delm-1,-335.410406,-670.970972,-489.588565,-3.381671,-7.161008,92.161494,58.931913,9.494694,-2.329122,...,0.740383,NaN,NaN,-0.416530,0.925338,2.197676,-2.258804,NaN,NaN,NaN

In [126]:
# # Baseline + Tap + PSA melted
# final_tstat_melted = pd.concat([combined_Tstats_normalized_melted, combined_Tstats_psa_melted]).drop_duplicates()

# final_tstat_melted.head()

## 4.2 Allele level 


- Pass Tap and baseline through merge_Tstats() as df3
- Pass PSA and baseline through merge_Tstats()as df4
- pd.merge df3 and df4 using all columns of basline

In [127]:
# Baseline + Tap
combined_Tstats_allele = merge_Tstats(PD_baseline_Tstats_allele,PD_habituation_Tstats_allele, "dataset")

In [128]:
# Baseline + PSA 
combined_Tstats_psa_allele = merge_Tstats(
    PD_baseline_Tstats_allele, psa_tstats_allele, by="dataset", psa=True
)

In [129]:
# Baseline + Tap + PSA
final_tstat_allele = pd.merge(combined_Tstats_allele.reset_index(), combined_Tstats_psa_allele.reset_index(), on = PD_baseline_Tstats_allele.columns.to_list().append(['dataset','Screen']), how = 'outer')
# final_tstat_allele = reorder_screencolumn(final_tstat_allele)
final_tstat_allele.head()

,dataset,Morphwidth,Midline,Area,Speed,Bias,Angular Speed,Aspect Ratio,Kink,Curve,...,Initial PSA Crab,Final PSA Crab,Recovery PSA Crab,Peak PSA Crab,Peak Tap Number of PSA Crab,Average PSA Crab,Sensitization of PSA Crab,Habituation of PSA Crab,Spontaneous Recovery of PSA Crab,Memory Retention of PSA Crab
0,AMshABLATE_nsIs109,8.436649,-72.062483,-19.016885,-170.402072,-129.051227,-72.427009,67.186598,60.225199,-59.206564,...,-1.626474,NaN,NaN,1.866463,2.236068,-1.688506,3.070526,NaN,NaN,NaN
1,N2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
2,ced-10_n3246,-96.420955,-590.226320,-328.825337,-178.516631,-101.994376,86.467808,324.132657,276.511600,81.799335,...,-5.665189,NaN,NaN,-0.997846,3.725065,-0.423095,1.107303,NaN,NaN,NaN
3,ced-5_n2002,-162.535954,-311.278255,-347.893201,-124.360515,-87.457709,6.824703,-59.527752,-97.326696,-156.138037,...,-5.649231,NaN,NaN,-2.451194,2.905970,-6.280971,-0.709694,NaN,NaN,NaN
4,delm-1_ok1226,-335.410406,-670.970972,-489.588565,-3.381671,-7.161008,92.161494,58.931913,9.494694,-2.329122,...,0.740383,NaN,NaN,-0.416530,0.925338,2.197676,-2.258804,NaN,NaN,NaN

In [130]:
final_tstat.shape

(22, 98)

In [131]:
# combined_MSD = reorder_screencolumn(combined_MSD)
# allele_combined_MSD = reorder_screencolumn(allele_combined_MSD)

In [132]:
# # Baseline + Tap + PSA melted
# final_tstat_melted_allele = pd.concat([combined_Tstats_normalized_melted_allele, combined_Tstats_psa_melted_allele]).drop_duplicates()

# final_tstat_melted_allele.head()

# 5. Save data to database (sqlite3)

#### A janky way to add data and update the sql 

1. Read table to pd.DataFrame
2. Add new data to pd.DataFrame
3. Replace old table with newly updated pd.DataFrame

# Primary Keys For Each SQL Table:

####  -- Gene_Allele_WormBaseID:
WBGene, WBAllele
#### -- alleleMSD:
dataset, Screen
#### -- gene_MSD:
Gene, Screen
#### -- allele_profile_data:
dataset, Metric, Screen
#### -- gene_profile_data:
Gene, Metric, Screen
#### -- tap_baseline_data:
Time, Plate_id, Date, Screen, dataset, Gene, Allele
#### -- tap_response_data:
Date, Plate_id, Screen, taps, dataset, Gene, Allele
#### -- tstat_allele_data:
dataset, Screen
#### -- tstat_gene_data:
Gene, Screen
#### -- psa_summarized_data:
Plate_id, Date ,Screen ,dataset ,Gene ,Allele

In [133]:
# print(tap_output.head(5))
# print(baseline_output.head(5))

tap_output.Screen = Screen
tap_psa_output.Screen = Screen
baseline_output.Screen = Screen

# print(tap_output.head(5))
# print(baseline_output.head(5))

In [134]:
# final_tstat_allele[final_tstat_allele.isna().any(axis=1)]
final_tstat_allele[final_tstat_allele["Morphwidth"].isna()]

Empty DataFrame
Columns: [dataset, Morphwidth, Midline, Area, Speed, Bias, Angular Speed, Aspect Ratio, Kink, Curve, Crab, Pathlength, Initial Response Duration, Initial Response Probability, Initial Response Speed, Final Response Duration, Final Response Probability, Final Response Speed, Habituation of Response Duration, Habituation of Response Probability, Habituation of Response Speed, Spontaneous Recovery of Response Duration, Spontaneous Recovery of Response Probability, Spontaneous Recovery of Response Speed, Memory Retention of Response Duration, Memory Retention of Response Probability, Memory Retention of Response Speed, Screen, Initial PSA Speed, Final PSA Speed, Recovery PSA Speed, Peak PSA Speed, Peak Tap Number of PSA Speed, Average PSA Speed, Sensitization of PSA Speed, Habituation of PSA Speed, Spontaneous Recovery of PSA Speed, Memory Retention of PSA Speed, Initial PSA Bias, Final PSA Bias, Recovery PSA Bias, Peak PSA Bias, Peak Tap Number of PSA Bias, Average PSA Bias, Sensitization of PSA Bias, Habituation of PSA Bias, Spontaneous Recovery of PSA Bias, Memory Retention of PSA Bias, Initial PSA Angular Speed, Final PSA Angular Speed, Recovery PSA Angular Speed, Peak PSA Angular Speed, Peak Tap Number of PSA Angular Speed, Average PSA Angular Speed, Sensitization of PSA Angular Speed, Habituation of PSA Angular Speed, Spontaneous Recovery of PSA Angular Speed, Memory Retention of PSA Angular Speed, Initial PSA Aspect Ratio, Final PSA Aspect Ratio, Recovery PSA Aspect Ratio, Peak PSA Aspect Ratio, Peak Tap Number of PSA Aspect Ratio, Average PSA Aspect Ratio, Sensitization of PSA Aspect Ratio, Habituation of PSA Aspect Ratio, Spontaneous Recovery of PSA Aspect Ratio, Memory Retention of PSA Aspect Ratio, Initial PSA Kink, Final PSA Kink, Recovery PSA Kink, Peak PSA Kink, Peak Tap Number of PSA Kink, Average PSA Kink, Sensitization of PSA Kink, Habituation of PSA Kink, Spontaneous Recovery of PSA Kink, Memory Retention of PSA Kink, Initial PSA Curve, Final PSA Curve, Recovery PSA Curve, Peak PSA Curve, Peak Tap Number of PSA Curve, Average PSA Curve, Sensitization of PSA Curve, Habituation of PSA Curve, Spontaneous Recovery of PSA Curve, Memory Retention of PSA Curve, Initial PSA Crab, Final PSA Crab, Recovery PSA Crab, Peak PSA Crab, Peak Tap Number of PSA Crab, Average PSA Crab, Sensitization of PSA Crab, Habituation of PSA Crab, Spontaneous Recovery of PSA Crab, Memory Retention of PSA Crab]
Index: []

[0 rows x 98 columns]

In [135]:
# final_tstat_allele[final_tstat_allele['dataset'] == "unknown_CZ11000"]

## Reorder columns before uploading

In [136]:
baseline_output = pd.concat([baseline_output[['Screen', 'dataset', 'Gene', 'Allele', 'Plate_id', 'Date']], 
                             baseline_output.drop(columns=['Screen', 'dataset', 'Gene', 'Allele', 'Plate_id', 'Date'])], axis=1)

tap_psa_output = pd.concat([tap_psa_output[['Screen', 'dataset', 'Gene', 'Allele', 'Plate_id', 'Date', 'taps']], 
                            tap_psa_output.drop(columns=['Screen', 'dataset', 'Gene', 'Allele', 'Plate_id', 'Date', 'taps'])],axis=1)

final_tstat = pd.concat([final_tstat[['Screen', 'Gene']], 
                         final_tstat.drop(columns = ['Screen', 'Gene'])], axis=1)

final_tstat_allele = pd.concat([final_tstat_allele[['Screen', 'dataset']], 
                                final_tstat_allele.drop(columns = ['Screen', 'dataset'])], axis=1)

combined_MSD = pd.concat([combined_MSD[['Screen', 'Gene']], 
                         combined_MSD.drop(columns = ['Screen', 'Gene'])], axis=1)

allele_combined_MSD = pd.concat([allele_combined_MSD[['Screen','dataset']], 
                         allele_combined_MSD.drop(columns = ['Screen','dataset'])], axis=1)

psa_data = pd.concat([psa_data[['Screen', 'dataset', 'Gene', 'Allele', 'Plate_id', 'Date']], 
                      psa_data.drop(columns=['Screen', 'dataset', 'Gene', 'Allele', 'Plate_id', 'Date'])], axis=1)

## Save to database

In [137]:

### This code will connect to PostgreSQL database and write non-duplicate data into the database tables.

# Loads database config values from database.ini file and validates that user and password are set.
config = load_config()
if (config['user'] == "" or config['password'] == ""):
    print("Please set your user and password in the database.ini file.")
    sys.exit(1)
    
# Creates a connection pool to PostgreSQL database using SQLAlchemy.
engine = create_engine(f"postgresql+psycopg://{config['user']}:{config['password']}@{config['host']}:{config['port']}/{config['database']}")

# Function to insert data into PostgreSQL table, skipping duplicates based on primary keys.
def postgres_skip_on_duplicate(pd_table, conn, keys, data_iter):
    data = [dict(zip(keys,row)) for row in data_iter]
    conn.execute(insert(pd_table.table).on_conflict_do_nothing(), data)

# --------- Write the dataframes to PostgreSQL tables -----------

# Complete tap response data
print("working on tap_psa_output:") 
tap_psa_output.to_sql('tap_response_data', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)
# tap_psa_output.to_sql('tap_response_data', engine, if_exists='replace', index=False, method=None)

# Complete baseline data  >NO
print("working on tap_baseline_data:") 
baseline_output.to_sql('tap_baseline_data', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)
# baseline_output.to_sql('tap_baseline_data', engine, if_exists='replace', index=False, method=None)

# Baseline + Tap + PSA combined tstat data by Gene
print("working on tstat_gene_data")
final_tstat.dropna(thresh=10).reset_index().to_sql('tstat_gene_data', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)
# final_tstat.reset_index().to_sql('tstat_gene_data', engine, if_exists='replace', index=False, method=None)

# Baseline + Tap + PSA combined tstat data by Allele
print("working on tstat_allele_data")
final_tstat_allele.dropna(thresh=10).reset_index().to_sql('tstat_allele_data', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)
# final_tstat_allele.reset_index().to_sql('tstat_allele_data', engine, if_exists='replace', index=False, method=None)

# MSD Baseline + Tap + PSA by Gene
print("working on gene_MSD")
combined_MSD.to_sql('gene_MSD', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)
# combined_MSD.to_sql('gene_MSD', engine, if_exists='replace', index=False, method=None)

# MSD Baseline + Tap + PSA by Allele
print("working on allele_MSD")
allele_combined_MSD.to_sql('allele_MSD', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)
# allele_combined_MSD.to_sql('allele_MSD', engine, if_exists='replace', index=False, method=None)

# Summarised PSA data (speed, kink, curve, etc.)
print("working on psa_data:") 
psa_data.to_sql('psa_summarised_data', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)
# psa_data.to_sql('psa_summarised_data', engine, if_exists='replace', index=False, method=None)

# # Melted Baseline + Tap + PSA combined tstat data by Gene
# print("working on gene_profile_data")
# final_tstat_melted.to_sql('gene_profile_data', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)

# # Melted Baseline + Tap + PSA combined tstat data by Allele
# print("working on allele_profile_data")
# final_tstat_melted_allele.to_sql('allele_profile_data', engine, if_exists='append', index=False, method=postgres_skip_on_duplicate)


print("---------- DONE ----------")

Please set your user and password in the database.ini file.

SystemExit: 1

### Use the below cell if you want output to local .csv file

In [138]:
# tap_psa_output.to_csv('/Users/Joseph/Desktop/PDScreen_tap_psa_output.csv', index=False)
# final_tstat.to_csv('/Users/Joseph/Desktop/PDScreen_final_tstat.csv', index=False)
# final_tstat_allele.to_csv('/Users/Joseph/Desktop/PDScreen_final_tstat_allele.csv', index=False)
# combined_MSD.to_csv('/Users/Joseph/Desktop/PDScreen_combined_MSD.csv', index=False)
# allele_combined_MSD.to_csv('/Users/Joseph/Desktop/PDScreen_combined_MSD_allele.csv', index=False)
# psa_data.to_csv('/Users/Joseph/Desktop/PDScreen_psa_data.csv', index=False)

### Use the below cell to just replace/update one table:

In [ ]:
# Loads database config values from database.ini file and validates that user and password are set.
config = load_config()
if (config['user'] == "" or config['password'] == ""):
    print("Please set your user and password in the database.ini file.")
    sys.exit(1)
    
# Creates a connection pool to PostgreSQL database using SQLAlchemy.
engine = create_engine(f"postgresql+psycopg://{config['user']}:{config['password']}@{config['host']}:{config['port']}/{config['database']}")

# Function to insert data into PostgreSQL table, skipping duplicates based on primary keys.
def postgres_skip_on_duplicate(pd_table, conn, keys, data_iter):
    data = [dict(zip(keys,row)) for row in data_iter]
    conn.execute(insert(pd_table.table).on_conflict_do_nothing(), data)


# Complete tap response data
print("working on tap_output:") 
tap_psa_output.to_sql('tap_response_data', engine, if_exists='replace', index=False, method=None)
print("Done")

In [ ]:
# # USE THIS CELL TO UPDATE ALL THE NEED TALBES (Also have baseline_output on the second line)

# conn=sqlite3.connect('/Users/lavanya/Desktop/Lavanya_Test/data_updated2.db')

# tap_output.to_sql('tap_response_data', conn, if_exists='append', index=False)

# baseline_output.to_sql('tap_baseline_data', conn, if_exists='append', index=False)

# combined_Tstats_normalize_2.reset_index().to_sql('tstat_gene_data', conn, if_exists='append', index=False)

# combined_Tstats_normalize_allele_2.reset_index().to_sql('tstat_allele_data', conn, if_exists='append', index=False)

# combined_Tstats_normalized_melted.to_sql('gene_profile_data', conn, if_exists='append', index=False)

# combined_Tstats_normalized_melted_allele.to_sql('allele_profile_data', conn, if_exists='append', index=False)

# combined_MSD.to_sql('gene_MSD', conn, if_exists='append', index=False)

# allele_combined_MSD.to_sql('allele_MSD', conn, if_exists='append', index=False)

# # combined_Tstats_melted_sorted.to_sql('allele_phenotype_data', conn, if_exists='replace', index=False)

# print(conn.total_changes)

# conn.close()


# # Want to test edge cases of pd.to_sql functionality#############